// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Openai
{
    public static class GetModels
    {
        /// <summary>
        /// Models data source
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Openai = Pulumi.Openai;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var models = Openai.GetModels.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["modelCount"] = models.Apply(getModelsResult =&gt; getModelsResult.Models).Length,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetModelsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetModelsResult>("openai:index/getModels:getModels", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Models data source
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Openai = Pulumi.Openai;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var models = Openai.GetModels.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["modelCount"] = models.Apply(getModelsResult =&gt; getModelsResult.Models).Length,
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetModelsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetModelsResult>("openai:index/getModels:getModels", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetModelsResult
    {
        /// <summary>
        /// Models identifier
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Models
        /// </summary>
        public readonly ImmutableArray<Outputs.GetModelsModelResult> Models;

        [OutputConstructor]
        private GetModelsResult(
            string id,

            ImmutableArray<Outputs.GetModelsModelResult> models)
        {
            Id = id;
            Models = models;
        }
    }
}
