// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package openai

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/tonkean/pulumi-openai/sdk/go/openai/internal"
)

// File resource
type File struct {
	pulumi.CustomResourceState

	// File size in bytes
	Bytes pulumi.IntOutput `pulumi:"bytes"`
	// Created Time
	Created pulumi.IntOutput `pulumi:"created"`
	// Filename
	Filename pulumi.StringOutput `pulumi:"filename"`
	// Filename
	Filepath pulumi.StringOutput `pulumi:"filepath"`
	// Object Type
	Object pulumi.StringOutput `pulumi:"object"`
	// Intended use of file. Use 'fine-tune' for Fine-tuning
	Purpose pulumi.StringOutput `pulumi:"purpose"`
}

// NewFile registers a new resource with the given unique name, arguments, and options.
func NewFile(ctx *pulumi.Context,
	name string, args *FileArgs, opts ...pulumi.ResourceOption) (*File, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Filepath == nil {
		return nil, errors.New("invalid value for required argument 'Filepath'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource File
	err := ctx.RegisterResource("openai:index/file:File", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFile gets an existing File resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFile(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FileState, opts ...pulumi.ResourceOption) (*File, error) {
	var resource File
	err := ctx.ReadResource("openai:index/file:File", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering File resources.
type fileState struct {
	// File size in bytes
	Bytes *int `pulumi:"bytes"`
	// Created Time
	Created *int `pulumi:"created"`
	// Filename
	Filename *string `pulumi:"filename"`
	// Filename
	Filepath *string `pulumi:"filepath"`
	// Object Type
	Object *string `pulumi:"object"`
	// Intended use of file. Use 'fine-tune' for Fine-tuning
	Purpose *string `pulumi:"purpose"`
}

type FileState struct {
	// File size in bytes
	Bytes pulumi.IntPtrInput
	// Created Time
	Created pulumi.IntPtrInput
	// Filename
	Filename pulumi.StringPtrInput
	// Filename
	Filepath pulumi.StringPtrInput
	// Object Type
	Object pulumi.StringPtrInput
	// Intended use of file. Use 'fine-tune' for Fine-tuning
	Purpose pulumi.StringPtrInput
}

func (FileState) ElementType() reflect.Type {
	return reflect.TypeOf((*fileState)(nil)).Elem()
}

type fileArgs struct {
	// Filename
	Filepath string `pulumi:"filepath"`
}

// The set of arguments for constructing a File resource.
type FileArgs struct {
	// Filename
	Filepath pulumi.StringInput
}

func (FileArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*fileArgs)(nil)).Elem()
}

type FileInput interface {
	pulumi.Input

	ToFileOutput() FileOutput
	ToFileOutputWithContext(ctx context.Context) FileOutput
}

func (*File) ElementType() reflect.Type {
	return reflect.TypeOf((**File)(nil)).Elem()
}

func (i *File) ToFileOutput() FileOutput {
	return i.ToFileOutputWithContext(context.Background())
}

func (i *File) ToFileOutputWithContext(ctx context.Context) FileOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FileOutput)
}

// FileArrayInput is an input type that accepts FileArray and FileArrayOutput values.
// You can construct a concrete instance of `FileArrayInput` via:
//
//	FileArray{ FileArgs{...} }
type FileArrayInput interface {
	pulumi.Input

	ToFileArrayOutput() FileArrayOutput
	ToFileArrayOutputWithContext(context.Context) FileArrayOutput
}

type FileArray []FileInput

func (FileArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*File)(nil)).Elem()
}

func (i FileArray) ToFileArrayOutput() FileArrayOutput {
	return i.ToFileArrayOutputWithContext(context.Background())
}

func (i FileArray) ToFileArrayOutputWithContext(ctx context.Context) FileArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FileArrayOutput)
}

// FileMapInput is an input type that accepts FileMap and FileMapOutput values.
// You can construct a concrete instance of `FileMapInput` via:
//
//	FileMap{ "key": FileArgs{...} }
type FileMapInput interface {
	pulumi.Input

	ToFileMapOutput() FileMapOutput
	ToFileMapOutputWithContext(context.Context) FileMapOutput
}

type FileMap map[string]FileInput

func (FileMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*File)(nil)).Elem()
}

func (i FileMap) ToFileMapOutput() FileMapOutput {
	return i.ToFileMapOutputWithContext(context.Background())
}

func (i FileMap) ToFileMapOutputWithContext(ctx context.Context) FileMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FileMapOutput)
}

type FileOutput struct{ *pulumi.OutputState }

func (FileOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**File)(nil)).Elem()
}

func (o FileOutput) ToFileOutput() FileOutput {
	return o
}

func (o FileOutput) ToFileOutputWithContext(ctx context.Context) FileOutput {
	return o
}

// File size in bytes
func (o FileOutput) Bytes() pulumi.IntOutput {
	return o.ApplyT(func(v *File) pulumi.IntOutput { return v.Bytes }).(pulumi.IntOutput)
}

// Created Time
func (o FileOutput) Created() pulumi.IntOutput {
	return o.ApplyT(func(v *File) pulumi.IntOutput { return v.Created }).(pulumi.IntOutput)
}

// Filename
func (o FileOutput) Filename() pulumi.StringOutput {
	return o.ApplyT(func(v *File) pulumi.StringOutput { return v.Filename }).(pulumi.StringOutput)
}

// Filename
func (o FileOutput) Filepath() pulumi.StringOutput {
	return o.ApplyT(func(v *File) pulumi.StringOutput { return v.Filepath }).(pulumi.StringOutput)
}

// Object Type
func (o FileOutput) Object() pulumi.StringOutput {
	return o.ApplyT(func(v *File) pulumi.StringOutput { return v.Object }).(pulumi.StringOutput)
}

// Intended use of file. Use 'fine-tune' for Fine-tuning
func (o FileOutput) Purpose() pulumi.StringOutput {
	return o.ApplyT(func(v *File) pulumi.StringOutput { return v.Purpose }).(pulumi.StringOutput)
}

type FileArrayOutput struct{ *pulumi.OutputState }

func (FileArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*File)(nil)).Elem()
}

func (o FileArrayOutput) ToFileArrayOutput() FileArrayOutput {
	return o
}

func (o FileArrayOutput) ToFileArrayOutputWithContext(ctx context.Context) FileArrayOutput {
	return o
}

func (o FileArrayOutput) Index(i pulumi.IntInput) FileOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *File {
		return vs[0].([]*File)[vs[1].(int)]
	}).(FileOutput)
}

type FileMapOutput struct{ *pulumi.OutputState }

func (FileMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*File)(nil)).Elem()
}

func (o FileMapOutput) ToFileMapOutput() FileMapOutput {
	return o
}

func (o FileMapOutput) ToFileMapOutputWithContext(ctx context.Context) FileMapOutput {
	return o
}

func (o FileMapOutput) MapIndex(k pulumi.StringInput) FileOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *File {
		return vs[0].(map[string]*File)[vs[1].(string)]
	}).(FileOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FileInput)(nil)).Elem(), &File{})
	pulumi.RegisterInputType(reflect.TypeOf((*FileArrayInput)(nil)).Elem(), FileArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*FileMapInput)(nil)).Elem(), FileMap{})
	pulumi.RegisterOutputType(FileOutput{})
	pulumi.RegisterOutputType(FileArrayOutput{})
	pulumi.RegisterOutputType(FileMapOutput{})
}
