// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package openai

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/tonkean/pulumi-openai/sdk/go/openai/internal"
)

// Files data source
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/tonkean/pulumi-openai/sdk/go/openai"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := openai.GetFiles(ctx, nil, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetFiles(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetFilesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetFilesResult
	err := ctx.Invoke("openai:index/getFiles:getFiles", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getFiles.
type GetFilesResult struct {
	// Files
	Files []GetFilesFile `pulumi:"files"`
	// Files identifier
	Id string `pulumi:"id"`
}

func GetFilesOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetFilesResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetFilesResult, error) {
		r, err := GetFiles(ctx, opts...)
		var s GetFilesResult
		if r != nil {
			s = *r
		}
		return s, err
	}).(GetFilesResultOutput)
}

// A collection of values returned by getFiles.
type GetFilesResultOutput struct{ *pulumi.OutputState }

func (GetFilesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFilesResult)(nil)).Elem()
}

func (o GetFilesResultOutput) ToGetFilesResultOutput() GetFilesResultOutput {
	return o
}

func (o GetFilesResultOutput) ToGetFilesResultOutputWithContext(ctx context.Context) GetFilesResultOutput {
	return o
}

// Files
func (o GetFilesResultOutput) Files() GetFilesFileArrayOutput {
	return o.ApplyT(func(v GetFilesResult) []GetFilesFile { return v.Files }).(GetFilesFileArrayOutput)
}

// Files identifier
func (o GetFilesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetFilesResult) string { return v.Id }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetFilesResultOutput{})
}
