// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package openai

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/tonkean/pulumi-openai/sdk/go/openai/internal"
)

// Fine-Tuning Jobs data source
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/tonkean/pulumi-openai/sdk/go/openai"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := openai.GetFinetuningJobs(ctx, nil, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetFinetuningJobs(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetFinetuningJobsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetFinetuningJobsResult
	err := ctx.Invoke("openai:index/getFinetuningJobs:getFinetuningJobs", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getFinetuningJobs.
type GetFinetuningJobsResult struct {
	// Fine-Tuning Jobs identifier
	Id string `pulumi:"id"`
	// Fine Tuning Jobs
	Jobs []GetFinetuningJobsJob `pulumi:"jobs"`
}

func GetFinetuningJobsOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetFinetuningJobsResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetFinetuningJobsResult, error) {
		r, err := GetFinetuningJobs(ctx, opts...)
		var s GetFinetuningJobsResult
		if r != nil {
			s = *r
		}
		return s, err
	}).(GetFinetuningJobsResultOutput)
}

// A collection of values returned by getFinetuningJobs.
type GetFinetuningJobsResultOutput struct{ *pulumi.OutputState }

func (GetFinetuningJobsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFinetuningJobsResult)(nil)).Elem()
}

func (o GetFinetuningJobsResultOutput) ToGetFinetuningJobsResultOutput() GetFinetuningJobsResultOutput {
	return o
}

func (o GetFinetuningJobsResultOutput) ToGetFinetuningJobsResultOutputWithContext(ctx context.Context) GetFinetuningJobsResultOutput {
	return o
}

// Fine-Tuning Jobs identifier
func (o GetFinetuningJobsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetFinetuningJobsResult) string { return v.Id }).(pulumi.StringOutput)
}

// Fine Tuning Jobs
func (o GetFinetuningJobsResultOutput) Jobs() GetFinetuningJobsJobArrayOutput {
	return o.ApplyT(func(v GetFinetuningJobsResult) []GetFinetuningJobsJob { return v.Jobs }).(GetFinetuningJobsJobArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetFinetuningJobsResultOutput{})
}
