// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package openai

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/tonkean/pulumi-openai/sdk/go/openai/internal"
)

// Fine-Tuning Job data source
func LookupFinetuningJob(ctx *pulumi.Context, args *LookupFinetuningJobArgs, opts ...pulumi.InvokeOption) (*LookupFinetuningJobResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupFinetuningJobResult
	err := ctx.Invoke("openai:index/getFinetuningJob:getFinetuningJob", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getFinetuningJob.
type LookupFinetuningJobArgs struct {
	// Fine Tuning Job Identifier
	Id string `pulumi:"id"`
}

// A collection of values returned by getFinetuningJob.
type LookupFinetuningJobResult struct {
	// Created Time
	CreatedAt int `pulumi:"createdAt"`
	// Fine-Tuned Model ID
	FineTunedModel string `pulumi:"fineTunedModel"`
	// Finished Time
	FinishedAt int `pulumi:"finishedAt"`
	// Hyperparams
	Hyperparams GetFinetuningJobHyperparams `pulumi:"hyperparams"`
	// Fine Tuning Job Identifier
	Id string `pulumi:"id"`
	// Model ID
	Model string `pulumi:"model"`
	// Object Type
	Object string `pulumi:"object"`
	// Organization ID
	OrganizationId string `pulumi:"organizationId"`
	// Result Files
	ResultFiles []string `pulumi:"resultFiles"`
	// Status
	Status string `pulumi:"status"`
	// Trained Tokens
	TrainedTokens int `pulumi:"trainedTokens"`
	// Training File
	TrainingFile string `pulumi:"trainingFile"`
	// Validation File
	ValidationFile string `pulumi:"validationFile"`
}

func LookupFinetuningJobOutput(ctx *pulumi.Context, args LookupFinetuningJobOutputArgs, opts ...pulumi.InvokeOption) LookupFinetuningJobResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupFinetuningJobResult, error) {
			args := v.(LookupFinetuningJobArgs)
			r, err := LookupFinetuningJob(ctx, &args, opts...)
			var s LookupFinetuningJobResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupFinetuningJobResultOutput)
}

// A collection of arguments for invoking getFinetuningJob.
type LookupFinetuningJobOutputArgs struct {
	// Fine Tuning Job Identifier
	Id pulumi.StringInput `pulumi:"id"`
}

func (LookupFinetuningJobOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFinetuningJobArgs)(nil)).Elem()
}

// A collection of values returned by getFinetuningJob.
type LookupFinetuningJobResultOutput struct{ *pulumi.OutputState }

func (LookupFinetuningJobResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFinetuningJobResult)(nil)).Elem()
}

func (o LookupFinetuningJobResultOutput) ToLookupFinetuningJobResultOutput() LookupFinetuningJobResultOutput {
	return o
}

func (o LookupFinetuningJobResultOutput) ToLookupFinetuningJobResultOutputWithContext(ctx context.Context) LookupFinetuningJobResultOutput {
	return o
}

// Created Time
func (o LookupFinetuningJobResultOutput) CreatedAt() pulumi.IntOutput {
	return o.ApplyT(func(v LookupFinetuningJobResult) int { return v.CreatedAt }).(pulumi.IntOutput)
}

// Fine-Tuned Model ID
func (o LookupFinetuningJobResultOutput) FineTunedModel() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFinetuningJobResult) string { return v.FineTunedModel }).(pulumi.StringOutput)
}

// Finished Time
func (o LookupFinetuningJobResultOutput) FinishedAt() pulumi.IntOutput {
	return o.ApplyT(func(v LookupFinetuningJobResult) int { return v.FinishedAt }).(pulumi.IntOutput)
}

// Hyperparams
func (o LookupFinetuningJobResultOutput) Hyperparams() GetFinetuningJobHyperparamsOutput {
	return o.ApplyT(func(v LookupFinetuningJobResult) GetFinetuningJobHyperparams { return v.Hyperparams }).(GetFinetuningJobHyperparamsOutput)
}

// Fine Tuning Job Identifier
func (o LookupFinetuningJobResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFinetuningJobResult) string { return v.Id }).(pulumi.StringOutput)
}

// Model ID
func (o LookupFinetuningJobResultOutput) Model() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFinetuningJobResult) string { return v.Model }).(pulumi.StringOutput)
}

// Object Type
func (o LookupFinetuningJobResultOutput) Object() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFinetuningJobResult) string { return v.Object }).(pulumi.StringOutput)
}

// Organization ID
func (o LookupFinetuningJobResultOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFinetuningJobResult) string { return v.OrganizationId }).(pulumi.StringOutput)
}

// Result Files
func (o LookupFinetuningJobResultOutput) ResultFiles() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupFinetuningJobResult) []string { return v.ResultFiles }).(pulumi.StringArrayOutput)
}

// Status
func (o LookupFinetuningJobResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFinetuningJobResult) string { return v.Status }).(pulumi.StringOutput)
}

// Trained Tokens
func (o LookupFinetuningJobResultOutput) TrainedTokens() pulumi.IntOutput {
	return o.ApplyT(func(v LookupFinetuningJobResult) int { return v.TrainedTokens }).(pulumi.IntOutput)
}

// Training File
func (o LookupFinetuningJobResultOutput) TrainingFile() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFinetuningJobResult) string { return v.TrainingFile }).(pulumi.StringOutput)
}

// Validation File
func (o LookupFinetuningJobResultOutput) ValidationFile() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFinetuningJobResult) string { return v.ValidationFile }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupFinetuningJobResultOutput{})
}
