// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package openai

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/tonkean/pulumi-openai/sdk/go/openai/internal"
)

// Model data source
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/tonkean/pulumi-openai/sdk/go/openai"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := openai.GetModel(ctx, &openai.GetModelArgs{
//				Id: "whisper-1",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetModel(ctx *pulumi.Context, args *GetModelArgs, opts ...pulumi.InvokeOption) (*GetModelResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetModelResult
	err := ctx.Invoke("openai:index/getModel:getModel", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getModel.
type GetModelArgs struct {
	// Model Identifier
	Id string `pulumi:"id"`
}

// A collection of values returned by getModel.
type GetModelResult struct {
	// Created Time
	Created int `pulumi:"created"`
	// Model Identifier
	Id string `pulumi:"id"`
	// Object Type
	Object string `pulumi:"object"`
	// Model Owner
	OwnedBy string `pulumi:"ownedBy"`
	// Parent
	Parent string `pulumi:"parent"`
	// Permissions
	Permissions []GetModelPermission `pulumi:"permissions"`
	// Root
	Root string `pulumi:"root"`
}

func GetModelOutput(ctx *pulumi.Context, args GetModelOutputArgs, opts ...pulumi.InvokeOption) GetModelResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetModelResult, error) {
			args := v.(GetModelArgs)
			r, err := GetModel(ctx, &args, opts...)
			var s GetModelResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetModelResultOutput)
}

// A collection of arguments for invoking getModel.
type GetModelOutputArgs struct {
	// Model Identifier
	Id pulumi.StringInput `pulumi:"id"`
}

func (GetModelOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetModelArgs)(nil)).Elem()
}

// A collection of values returned by getModel.
type GetModelResultOutput struct{ *pulumi.OutputState }

func (GetModelResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetModelResult)(nil)).Elem()
}

func (o GetModelResultOutput) ToGetModelResultOutput() GetModelResultOutput {
	return o
}

func (o GetModelResultOutput) ToGetModelResultOutputWithContext(ctx context.Context) GetModelResultOutput {
	return o
}

// Created Time
func (o GetModelResultOutput) Created() pulumi.IntOutput {
	return o.ApplyT(func(v GetModelResult) int { return v.Created }).(pulumi.IntOutput)
}

// Model Identifier
func (o GetModelResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelResult) string { return v.Id }).(pulumi.StringOutput)
}

// Object Type
func (o GetModelResultOutput) Object() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelResult) string { return v.Object }).(pulumi.StringOutput)
}

// Model Owner
func (o GetModelResultOutput) OwnedBy() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelResult) string { return v.OwnedBy }).(pulumi.StringOutput)
}

// Parent
func (o GetModelResultOutput) Parent() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelResult) string { return v.Parent }).(pulumi.StringOutput)
}

// Permissions
func (o GetModelResultOutput) Permissions() GetModelPermissionArrayOutput {
	return o.ApplyT(func(v GetModelResult) []GetModelPermission { return v.Permissions }).(GetModelPermissionArrayOutput)
}

// Root
func (o GetModelResultOutput) Root() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelResult) string { return v.Root }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetModelResultOutput{})
}
