// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package openai

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/tonkean/pulumi-openai/sdk/go/openai/internal"
)

var _ = internal.GetEnvOrDefault

type AssistantTool struct {
	// Function definition for tools of type function.
	Function *AssistantToolFunction `pulumi:"function"`
	// Tools can be of types code_interpreter, retrieval, or function.
	Type string `pulumi:"type"`
}

// AssistantToolInput is an input type that accepts AssistantToolArgs and AssistantToolOutput values.
// You can construct a concrete instance of `AssistantToolInput` via:
//
//	AssistantToolArgs{...}
type AssistantToolInput interface {
	pulumi.Input

	ToAssistantToolOutput() AssistantToolOutput
	ToAssistantToolOutputWithContext(context.Context) AssistantToolOutput
}

type AssistantToolArgs struct {
	// Function definition for tools of type function.
	Function AssistantToolFunctionPtrInput `pulumi:"function"`
	// Tools can be of types code_interpreter, retrieval, or function.
	Type pulumi.StringInput `pulumi:"type"`
}

func (AssistantToolArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AssistantTool)(nil)).Elem()
}

func (i AssistantToolArgs) ToAssistantToolOutput() AssistantToolOutput {
	return i.ToAssistantToolOutputWithContext(context.Background())
}

func (i AssistantToolArgs) ToAssistantToolOutputWithContext(ctx context.Context) AssistantToolOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AssistantToolOutput)
}

// AssistantToolArrayInput is an input type that accepts AssistantToolArray and AssistantToolArrayOutput values.
// You can construct a concrete instance of `AssistantToolArrayInput` via:
//
//	AssistantToolArray{ AssistantToolArgs{...} }
type AssistantToolArrayInput interface {
	pulumi.Input

	ToAssistantToolArrayOutput() AssistantToolArrayOutput
	ToAssistantToolArrayOutputWithContext(context.Context) AssistantToolArrayOutput
}

type AssistantToolArray []AssistantToolInput

func (AssistantToolArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]AssistantTool)(nil)).Elem()
}

func (i AssistantToolArray) ToAssistantToolArrayOutput() AssistantToolArrayOutput {
	return i.ToAssistantToolArrayOutputWithContext(context.Background())
}

func (i AssistantToolArray) ToAssistantToolArrayOutputWithContext(ctx context.Context) AssistantToolArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AssistantToolArrayOutput)
}

type AssistantToolOutput struct{ *pulumi.OutputState }

func (AssistantToolOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AssistantTool)(nil)).Elem()
}

func (o AssistantToolOutput) ToAssistantToolOutput() AssistantToolOutput {
	return o
}

func (o AssistantToolOutput) ToAssistantToolOutputWithContext(ctx context.Context) AssistantToolOutput {
	return o
}

// Function definition for tools of type function.
func (o AssistantToolOutput) Function() AssistantToolFunctionPtrOutput {
	return o.ApplyT(func(v AssistantTool) *AssistantToolFunction { return v.Function }).(AssistantToolFunctionPtrOutput)
}

// Tools can be of types code_interpreter, retrieval, or function.
func (o AssistantToolOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v AssistantTool) string { return v.Type }).(pulumi.StringOutput)
}

type AssistantToolArrayOutput struct{ *pulumi.OutputState }

func (AssistantToolArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]AssistantTool)(nil)).Elem()
}

func (o AssistantToolArrayOutput) ToAssistantToolArrayOutput() AssistantToolArrayOutput {
	return o
}

func (o AssistantToolArrayOutput) ToAssistantToolArrayOutputWithContext(ctx context.Context) AssistantToolArrayOutput {
	return o
}

func (o AssistantToolArrayOutput) Index(i pulumi.IntInput) AssistantToolOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) AssistantTool {
		return vs[0].([]AssistantTool)[vs[1].(int)]
	}).(AssistantToolOutput)
}

type AssistantToolFunction struct {
	// A description of what the function does, used by the model to choose when and how to call the function.
	Description *string `pulumi:"description"`
	// The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.
	Name string `pulumi:"name"`
	// The parameters the functions accepts, described as a JSON Schema object.
	Parameters string `pulumi:"parameters"`
}

// AssistantToolFunctionInput is an input type that accepts AssistantToolFunctionArgs and AssistantToolFunctionOutput values.
// You can construct a concrete instance of `AssistantToolFunctionInput` via:
//
//	AssistantToolFunctionArgs{...}
type AssistantToolFunctionInput interface {
	pulumi.Input

	ToAssistantToolFunctionOutput() AssistantToolFunctionOutput
	ToAssistantToolFunctionOutputWithContext(context.Context) AssistantToolFunctionOutput
}

type AssistantToolFunctionArgs struct {
	// A description of what the function does, used by the model to choose when and how to call the function.
	Description pulumi.StringPtrInput `pulumi:"description"`
	// The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.
	Name pulumi.StringInput `pulumi:"name"`
	// The parameters the functions accepts, described as a JSON Schema object.
	Parameters pulumi.StringInput `pulumi:"parameters"`
}

func (AssistantToolFunctionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AssistantToolFunction)(nil)).Elem()
}

func (i AssistantToolFunctionArgs) ToAssistantToolFunctionOutput() AssistantToolFunctionOutput {
	return i.ToAssistantToolFunctionOutputWithContext(context.Background())
}

func (i AssistantToolFunctionArgs) ToAssistantToolFunctionOutputWithContext(ctx context.Context) AssistantToolFunctionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AssistantToolFunctionOutput)
}

func (i AssistantToolFunctionArgs) ToAssistantToolFunctionPtrOutput() AssistantToolFunctionPtrOutput {
	return i.ToAssistantToolFunctionPtrOutputWithContext(context.Background())
}

func (i AssistantToolFunctionArgs) ToAssistantToolFunctionPtrOutputWithContext(ctx context.Context) AssistantToolFunctionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AssistantToolFunctionOutput).ToAssistantToolFunctionPtrOutputWithContext(ctx)
}

// AssistantToolFunctionPtrInput is an input type that accepts AssistantToolFunctionArgs, AssistantToolFunctionPtr and AssistantToolFunctionPtrOutput values.
// You can construct a concrete instance of `AssistantToolFunctionPtrInput` via:
//
//	        AssistantToolFunctionArgs{...}
//
//	or:
//
//	        nil
type AssistantToolFunctionPtrInput interface {
	pulumi.Input

	ToAssistantToolFunctionPtrOutput() AssistantToolFunctionPtrOutput
	ToAssistantToolFunctionPtrOutputWithContext(context.Context) AssistantToolFunctionPtrOutput
}

type assistantToolFunctionPtrType AssistantToolFunctionArgs

func AssistantToolFunctionPtr(v *AssistantToolFunctionArgs) AssistantToolFunctionPtrInput {
	return (*assistantToolFunctionPtrType)(v)
}

func (*assistantToolFunctionPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**AssistantToolFunction)(nil)).Elem()
}

func (i *assistantToolFunctionPtrType) ToAssistantToolFunctionPtrOutput() AssistantToolFunctionPtrOutput {
	return i.ToAssistantToolFunctionPtrOutputWithContext(context.Background())
}

func (i *assistantToolFunctionPtrType) ToAssistantToolFunctionPtrOutputWithContext(ctx context.Context) AssistantToolFunctionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AssistantToolFunctionPtrOutput)
}

type AssistantToolFunctionOutput struct{ *pulumi.OutputState }

func (AssistantToolFunctionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AssistantToolFunction)(nil)).Elem()
}

func (o AssistantToolFunctionOutput) ToAssistantToolFunctionOutput() AssistantToolFunctionOutput {
	return o
}

func (o AssistantToolFunctionOutput) ToAssistantToolFunctionOutputWithContext(ctx context.Context) AssistantToolFunctionOutput {
	return o
}

func (o AssistantToolFunctionOutput) ToAssistantToolFunctionPtrOutput() AssistantToolFunctionPtrOutput {
	return o.ToAssistantToolFunctionPtrOutputWithContext(context.Background())
}

func (o AssistantToolFunctionOutput) ToAssistantToolFunctionPtrOutputWithContext(ctx context.Context) AssistantToolFunctionPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v AssistantToolFunction) *AssistantToolFunction {
		return &v
	}).(AssistantToolFunctionPtrOutput)
}

// A description of what the function does, used by the model to choose when and how to call the function.
func (o AssistantToolFunctionOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v AssistantToolFunction) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.
func (o AssistantToolFunctionOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v AssistantToolFunction) string { return v.Name }).(pulumi.StringOutput)
}

// The parameters the functions accepts, described as a JSON Schema object.
func (o AssistantToolFunctionOutput) Parameters() pulumi.StringOutput {
	return o.ApplyT(func(v AssistantToolFunction) string { return v.Parameters }).(pulumi.StringOutput)
}

type AssistantToolFunctionPtrOutput struct{ *pulumi.OutputState }

func (AssistantToolFunctionPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AssistantToolFunction)(nil)).Elem()
}

func (o AssistantToolFunctionPtrOutput) ToAssistantToolFunctionPtrOutput() AssistantToolFunctionPtrOutput {
	return o
}

func (o AssistantToolFunctionPtrOutput) ToAssistantToolFunctionPtrOutputWithContext(ctx context.Context) AssistantToolFunctionPtrOutput {
	return o
}

func (o AssistantToolFunctionPtrOutput) Elem() AssistantToolFunctionOutput {
	return o.ApplyT(func(v *AssistantToolFunction) AssistantToolFunction {
		if v != nil {
			return *v
		}
		var ret AssistantToolFunction
		return ret
	}).(AssistantToolFunctionOutput)
}

// A description of what the function does, used by the model to choose when and how to call the function.
func (o AssistantToolFunctionPtrOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AssistantToolFunction) *string {
		if v == nil {
			return nil
		}
		return v.Description
	}).(pulumi.StringPtrOutput)
}

// The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.
func (o AssistantToolFunctionPtrOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AssistantToolFunction) *string {
		if v == nil {
			return nil
		}
		return &v.Name
	}).(pulumi.StringPtrOutput)
}

// The parameters the functions accepts, described as a JSON Schema object.
func (o AssistantToolFunctionPtrOutput) Parameters() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AssistantToolFunction) *string {
		if v == nil {
			return nil
		}
		return &v.Parameters
	}).(pulumi.StringPtrOutput)
}

type AssistantToolResources struct {
	// Function definition for tools of type function.
	CodeInterpreter *AssistantToolResourcesCodeInterpreter `pulumi:"codeInterpreter"`
	// Function definition for tools of type function.
	FileSearch *AssistantToolResourcesFileSearch `pulumi:"fileSearch"`
}

// AssistantToolResourcesInput is an input type that accepts AssistantToolResourcesArgs and AssistantToolResourcesOutput values.
// You can construct a concrete instance of `AssistantToolResourcesInput` via:
//
//	AssistantToolResourcesArgs{...}
type AssistantToolResourcesInput interface {
	pulumi.Input

	ToAssistantToolResourcesOutput() AssistantToolResourcesOutput
	ToAssistantToolResourcesOutputWithContext(context.Context) AssistantToolResourcesOutput
}

type AssistantToolResourcesArgs struct {
	// Function definition for tools of type function.
	CodeInterpreter AssistantToolResourcesCodeInterpreterPtrInput `pulumi:"codeInterpreter"`
	// Function definition for tools of type function.
	FileSearch AssistantToolResourcesFileSearchPtrInput `pulumi:"fileSearch"`
}

func (AssistantToolResourcesArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AssistantToolResources)(nil)).Elem()
}

func (i AssistantToolResourcesArgs) ToAssistantToolResourcesOutput() AssistantToolResourcesOutput {
	return i.ToAssistantToolResourcesOutputWithContext(context.Background())
}

func (i AssistantToolResourcesArgs) ToAssistantToolResourcesOutputWithContext(ctx context.Context) AssistantToolResourcesOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AssistantToolResourcesOutput)
}

func (i AssistantToolResourcesArgs) ToAssistantToolResourcesPtrOutput() AssistantToolResourcesPtrOutput {
	return i.ToAssistantToolResourcesPtrOutputWithContext(context.Background())
}

func (i AssistantToolResourcesArgs) ToAssistantToolResourcesPtrOutputWithContext(ctx context.Context) AssistantToolResourcesPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AssistantToolResourcesOutput).ToAssistantToolResourcesPtrOutputWithContext(ctx)
}

// AssistantToolResourcesPtrInput is an input type that accepts AssistantToolResourcesArgs, AssistantToolResourcesPtr and AssistantToolResourcesPtrOutput values.
// You can construct a concrete instance of `AssistantToolResourcesPtrInput` via:
//
//	        AssistantToolResourcesArgs{...}
//
//	or:
//
//	        nil
type AssistantToolResourcesPtrInput interface {
	pulumi.Input

	ToAssistantToolResourcesPtrOutput() AssistantToolResourcesPtrOutput
	ToAssistantToolResourcesPtrOutputWithContext(context.Context) AssistantToolResourcesPtrOutput
}

type assistantToolResourcesPtrType AssistantToolResourcesArgs

func AssistantToolResourcesPtr(v *AssistantToolResourcesArgs) AssistantToolResourcesPtrInput {
	return (*assistantToolResourcesPtrType)(v)
}

func (*assistantToolResourcesPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**AssistantToolResources)(nil)).Elem()
}

func (i *assistantToolResourcesPtrType) ToAssistantToolResourcesPtrOutput() AssistantToolResourcesPtrOutput {
	return i.ToAssistantToolResourcesPtrOutputWithContext(context.Background())
}

func (i *assistantToolResourcesPtrType) ToAssistantToolResourcesPtrOutputWithContext(ctx context.Context) AssistantToolResourcesPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AssistantToolResourcesPtrOutput)
}

type AssistantToolResourcesOutput struct{ *pulumi.OutputState }

func (AssistantToolResourcesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AssistantToolResources)(nil)).Elem()
}

func (o AssistantToolResourcesOutput) ToAssistantToolResourcesOutput() AssistantToolResourcesOutput {
	return o
}

func (o AssistantToolResourcesOutput) ToAssistantToolResourcesOutputWithContext(ctx context.Context) AssistantToolResourcesOutput {
	return o
}

func (o AssistantToolResourcesOutput) ToAssistantToolResourcesPtrOutput() AssistantToolResourcesPtrOutput {
	return o.ToAssistantToolResourcesPtrOutputWithContext(context.Background())
}

func (o AssistantToolResourcesOutput) ToAssistantToolResourcesPtrOutputWithContext(ctx context.Context) AssistantToolResourcesPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v AssistantToolResources) *AssistantToolResources {
		return &v
	}).(AssistantToolResourcesPtrOutput)
}

// Function definition for tools of type function.
func (o AssistantToolResourcesOutput) CodeInterpreter() AssistantToolResourcesCodeInterpreterPtrOutput {
	return o.ApplyT(func(v AssistantToolResources) *AssistantToolResourcesCodeInterpreter { return v.CodeInterpreter }).(AssistantToolResourcesCodeInterpreterPtrOutput)
}

// Function definition for tools of type function.
func (o AssistantToolResourcesOutput) FileSearch() AssistantToolResourcesFileSearchPtrOutput {
	return o.ApplyT(func(v AssistantToolResources) *AssistantToolResourcesFileSearch { return v.FileSearch }).(AssistantToolResourcesFileSearchPtrOutput)
}

type AssistantToolResourcesPtrOutput struct{ *pulumi.OutputState }

func (AssistantToolResourcesPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AssistantToolResources)(nil)).Elem()
}

func (o AssistantToolResourcesPtrOutput) ToAssistantToolResourcesPtrOutput() AssistantToolResourcesPtrOutput {
	return o
}

func (o AssistantToolResourcesPtrOutput) ToAssistantToolResourcesPtrOutputWithContext(ctx context.Context) AssistantToolResourcesPtrOutput {
	return o
}

func (o AssistantToolResourcesPtrOutput) Elem() AssistantToolResourcesOutput {
	return o.ApplyT(func(v *AssistantToolResources) AssistantToolResources {
		if v != nil {
			return *v
		}
		var ret AssistantToolResources
		return ret
	}).(AssistantToolResourcesOutput)
}

// Function definition for tools of type function.
func (o AssistantToolResourcesPtrOutput) CodeInterpreter() AssistantToolResourcesCodeInterpreterPtrOutput {
	return o.ApplyT(func(v *AssistantToolResources) *AssistantToolResourcesCodeInterpreter {
		if v == nil {
			return nil
		}
		return v.CodeInterpreter
	}).(AssistantToolResourcesCodeInterpreterPtrOutput)
}

// Function definition for tools of type function.
func (o AssistantToolResourcesPtrOutput) FileSearch() AssistantToolResourcesFileSearchPtrOutput {
	return o.ApplyT(func(v *AssistantToolResources) *AssistantToolResourcesFileSearch {
		if v == nil {
			return nil
		}
		return v.FileSearch
	}).(AssistantToolResourcesFileSearchPtrOutput)
}

type AssistantToolResourcesCodeInterpreter struct {
	// A list of file IDs attached to this assistant. There can be a maximum of 20 files attached to the assistant. Files are ordered by their creation date in ascending order.
	FileIds []string `pulumi:"fileIds"`
}

// AssistantToolResourcesCodeInterpreterInput is an input type that accepts AssistantToolResourcesCodeInterpreterArgs and AssistantToolResourcesCodeInterpreterOutput values.
// You can construct a concrete instance of `AssistantToolResourcesCodeInterpreterInput` via:
//
//	AssistantToolResourcesCodeInterpreterArgs{...}
type AssistantToolResourcesCodeInterpreterInput interface {
	pulumi.Input

	ToAssistantToolResourcesCodeInterpreterOutput() AssistantToolResourcesCodeInterpreterOutput
	ToAssistantToolResourcesCodeInterpreterOutputWithContext(context.Context) AssistantToolResourcesCodeInterpreterOutput
}

type AssistantToolResourcesCodeInterpreterArgs struct {
	// A list of file IDs attached to this assistant. There can be a maximum of 20 files attached to the assistant. Files are ordered by their creation date in ascending order.
	FileIds pulumi.StringArrayInput `pulumi:"fileIds"`
}

func (AssistantToolResourcesCodeInterpreterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AssistantToolResourcesCodeInterpreter)(nil)).Elem()
}

func (i AssistantToolResourcesCodeInterpreterArgs) ToAssistantToolResourcesCodeInterpreterOutput() AssistantToolResourcesCodeInterpreterOutput {
	return i.ToAssistantToolResourcesCodeInterpreterOutputWithContext(context.Background())
}

func (i AssistantToolResourcesCodeInterpreterArgs) ToAssistantToolResourcesCodeInterpreterOutputWithContext(ctx context.Context) AssistantToolResourcesCodeInterpreterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AssistantToolResourcesCodeInterpreterOutput)
}

func (i AssistantToolResourcesCodeInterpreterArgs) ToAssistantToolResourcesCodeInterpreterPtrOutput() AssistantToolResourcesCodeInterpreterPtrOutput {
	return i.ToAssistantToolResourcesCodeInterpreterPtrOutputWithContext(context.Background())
}

func (i AssistantToolResourcesCodeInterpreterArgs) ToAssistantToolResourcesCodeInterpreterPtrOutputWithContext(ctx context.Context) AssistantToolResourcesCodeInterpreterPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AssistantToolResourcesCodeInterpreterOutput).ToAssistantToolResourcesCodeInterpreterPtrOutputWithContext(ctx)
}

// AssistantToolResourcesCodeInterpreterPtrInput is an input type that accepts AssistantToolResourcesCodeInterpreterArgs, AssistantToolResourcesCodeInterpreterPtr and AssistantToolResourcesCodeInterpreterPtrOutput values.
// You can construct a concrete instance of `AssistantToolResourcesCodeInterpreterPtrInput` via:
//
//	        AssistantToolResourcesCodeInterpreterArgs{...}
//
//	or:
//
//	        nil
type AssistantToolResourcesCodeInterpreterPtrInput interface {
	pulumi.Input

	ToAssistantToolResourcesCodeInterpreterPtrOutput() AssistantToolResourcesCodeInterpreterPtrOutput
	ToAssistantToolResourcesCodeInterpreterPtrOutputWithContext(context.Context) AssistantToolResourcesCodeInterpreterPtrOutput
}

type assistantToolResourcesCodeInterpreterPtrType AssistantToolResourcesCodeInterpreterArgs

func AssistantToolResourcesCodeInterpreterPtr(v *AssistantToolResourcesCodeInterpreterArgs) AssistantToolResourcesCodeInterpreterPtrInput {
	return (*assistantToolResourcesCodeInterpreterPtrType)(v)
}

func (*assistantToolResourcesCodeInterpreterPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**AssistantToolResourcesCodeInterpreter)(nil)).Elem()
}

func (i *assistantToolResourcesCodeInterpreterPtrType) ToAssistantToolResourcesCodeInterpreterPtrOutput() AssistantToolResourcesCodeInterpreterPtrOutput {
	return i.ToAssistantToolResourcesCodeInterpreterPtrOutputWithContext(context.Background())
}

func (i *assistantToolResourcesCodeInterpreterPtrType) ToAssistantToolResourcesCodeInterpreterPtrOutputWithContext(ctx context.Context) AssistantToolResourcesCodeInterpreterPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AssistantToolResourcesCodeInterpreterPtrOutput)
}

type AssistantToolResourcesCodeInterpreterOutput struct{ *pulumi.OutputState }

func (AssistantToolResourcesCodeInterpreterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AssistantToolResourcesCodeInterpreter)(nil)).Elem()
}

func (o AssistantToolResourcesCodeInterpreterOutput) ToAssistantToolResourcesCodeInterpreterOutput() AssistantToolResourcesCodeInterpreterOutput {
	return o
}

func (o AssistantToolResourcesCodeInterpreterOutput) ToAssistantToolResourcesCodeInterpreterOutputWithContext(ctx context.Context) AssistantToolResourcesCodeInterpreterOutput {
	return o
}

func (o AssistantToolResourcesCodeInterpreterOutput) ToAssistantToolResourcesCodeInterpreterPtrOutput() AssistantToolResourcesCodeInterpreterPtrOutput {
	return o.ToAssistantToolResourcesCodeInterpreterPtrOutputWithContext(context.Background())
}

func (o AssistantToolResourcesCodeInterpreterOutput) ToAssistantToolResourcesCodeInterpreterPtrOutputWithContext(ctx context.Context) AssistantToolResourcesCodeInterpreterPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v AssistantToolResourcesCodeInterpreter) *AssistantToolResourcesCodeInterpreter {
		return &v
	}).(AssistantToolResourcesCodeInterpreterPtrOutput)
}

// A list of file IDs attached to this assistant. There can be a maximum of 20 files attached to the assistant. Files are ordered by their creation date in ascending order.
func (o AssistantToolResourcesCodeInterpreterOutput) FileIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v AssistantToolResourcesCodeInterpreter) []string { return v.FileIds }).(pulumi.StringArrayOutput)
}

type AssistantToolResourcesCodeInterpreterPtrOutput struct{ *pulumi.OutputState }

func (AssistantToolResourcesCodeInterpreterPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AssistantToolResourcesCodeInterpreter)(nil)).Elem()
}

func (o AssistantToolResourcesCodeInterpreterPtrOutput) ToAssistantToolResourcesCodeInterpreterPtrOutput() AssistantToolResourcesCodeInterpreterPtrOutput {
	return o
}

func (o AssistantToolResourcesCodeInterpreterPtrOutput) ToAssistantToolResourcesCodeInterpreterPtrOutputWithContext(ctx context.Context) AssistantToolResourcesCodeInterpreterPtrOutput {
	return o
}

func (o AssistantToolResourcesCodeInterpreterPtrOutput) Elem() AssistantToolResourcesCodeInterpreterOutput {
	return o.ApplyT(func(v *AssistantToolResourcesCodeInterpreter) AssistantToolResourcesCodeInterpreter {
		if v != nil {
			return *v
		}
		var ret AssistantToolResourcesCodeInterpreter
		return ret
	}).(AssistantToolResourcesCodeInterpreterOutput)
}

// A list of file IDs attached to this assistant. There can be a maximum of 20 files attached to the assistant. Files are ordered by their creation date in ascending order.
func (o AssistantToolResourcesCodeInterpreterPtrOutput) FileIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AssistantToolResourcesCodeInterpreter) []string {
		if v == nil {
			return nil
		}
		return v.FileIds
	}).(pulumi.StringArrayOutput)
}

type AssistantToolResourcesFileSearch struct {
	// A list of file IDs attached to this assistant. There can be a maximum of 20 files attached to the assistant. Files are ordered by their creation date in ascending order.
	VectorStoreIds []string `pulumi:"vectorStoreIds"`
	// Function definition for tools of type function.
	VectorStores *AssistantToolResourcesFileSearchVectorStores `pulumi:"vectorStores"`
}

// AssistantToolResourcesFileSearchInput is an input type that accepts AssistantToolResourcesFileSearchArgs and AssistantToolResourcesFileSearchOutput values.
// You can construct a concrete instance of `AssistantToolResourcesFileSearchInput` via:
//
//	AssistantToolResourcesFileSearchArgs{...}
type AssistantToolResourcesFileSearchInput interface {
	pulumi.Input

	ToAssistantToolResourcesFileSearchOutput() AssistantToolResourcesFileSearchOutput
	ToAssistantToolResourcesFileSearchOutputWithContext(context.Context) AssistantToolResourcesFileSearchOutput
}

type AssistantToolResourcesFileSearchArgs struct {
	// A list of file IDs attached to this assistant. There can be a maximum of 20 files attached to the assistant. Files are ordered by their creation date in ascending order.
	VectorStoreIds pulumi.StringArrayInput `pulumi:"vectorStoreIds"`
	// Function definition for tools of type function.
	VectorStores AssistantToolResourcesFileSearchVectorStoresPtrInput `pulumi:"vectorStores"`
}

func (AssistantToolResourcesFileSearchArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AssistantToolResourcesFileSearch)(nil)).Elem()
}

func (i AssistantToolResourcesFileSearchArgs) ToAssistantToolResourcesFileSearchOutput() AssistantToolResourcesFileSearchOutput {
	return i.ToAssistantToolResourcesFileSearchOutputWithContext(context.Background())
}

func (i AssistantToolResourcesFileSearchArgs) ToAssistantToolResourcesFileSearchOutputWithContext(ctx context.Context) AssistantToolResourcesFileSearchOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AssistantToolResourcesFileSearchOutput)
}

func (i AssistantToolResourcesFileSearchArgs) ToAssistantToolResourcesFileSearchPtrOutput() AssistantToolResourcesFileSearchPtrOutput {
	return i.ToAssistantToolResourcesFileSearchPtrOutputWithContext(context.Background())
}

func (i AssistantToolResourcesFileSearchArgs) ToAssistantToolResourcesFileSearchPtrOutputWithContext(ctx context.Context) AssistantToolResourcesFileSearchPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AssistantToolResourcesFileSearchOutput).ToAssistantToolResourcesFileSearchPtrOutputWithContext(ctx)
}

// AssistantToolResourcesFileSearchPtrInput is an input type that accepts AssistantToolResourcesFileSearchArgs, AssistantToolResourcesFileSearchPtr and AssistantToolResourcesFileSearchPtrOutput values.
// You can construct a concrete instance of `AssistantToolResourcesFileSearchPtrInput` via:
//
//	        AssistantToolResourcesFileSearchArgs{...}
//
//	or:
//
//	        nil
type AssistantToolResourcesFileSearchPtrInput interface {
	pulumi.Input

	ToAssistantToolResourcesFileSearchPtrOutput() AssistantToolResourcesFileSearchPtrOutput
	ToAssistantToolResourcesFileSearchPtrOutputWithContext(context.Context) AssistantToolResourcesFileSearchPtrOutput
}

type assistantToolResourcesFileSearchPtrType AssistantToolResourcesFileSearchArgs

func AssistantToolResourcesFileSearchPtr(v *AssistantToolResourcesFileSearchArgs) AssistantToolResourcesFileSearchPtrInput {
	return (*assistantToolResourcesFileSearchPtrType)(v)
}

func (*assistantToolResourcesFileSearchPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**AssistantToolResourcesFileSearch)(nil)).Elem()
}

func (i *assistantToolResourcesFileSearchPtrType) ToAssistantToolResourcesFileSearchPtrOutput() AssistantToolResourcesFileSearchPtrOutput {
	return i.ToAssistantToolResourcesFileSearchPtrOutputWithContext(context.Background())
}

func (i *assistantToolResourcesFileSearchPtrType) ToAssistantToolResourcesFileSearchPtrOutputWithContext(ctx context.Context) AssistantToolResourcesFileSearchPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AssistantToolResourcesFileSearchPtrOutput)
}

type AssistantToolResourcesFileSearchOutput struct{ *pulumi.OutputState }

func (AssistantToolResourcesFileSearchOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AssistantToolResourcesFileSearch)(nil)).Elem()
}

func (o AssistantToolResourcesFileSearchOutput) ToAssistantToolResourcesFileSearchOutput() AssistantToolResourcesFileSearchOutput {
	return o
}

func (o AssistantToolResourcesFileSearchOutput) ToAssistantToolResourcesFileSearchOutputWithContext(ctx context.Context) AssistantToolResourcesFileSearchOutput {
	return o
}

func (o AssistantToolResourcesFileSearchOutput) ToAssistantToolResourcesFileSearchPtrOutput() AssistantToolResourcesFileSearchPtrOutput {
	return o.ToAssistantToolResourcesFileSearchPtrOutputWithContext(context.Background())
}

func (o AssistantToolResourcesFileSearchOutput) ToAssistantToolResourcesFileSearchPtrOutputWithContext(ctx context.Context) AssistantToolResourcesFileSearchPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v AssistantToolResourcesFileSearch) *AssistantToolResourcesFileSearch {
		return &v
	}).(AssistantToolResourcesFileSearchPtrOutput)
}

// A list of file IDs attached to this assistant. There can be a maximum of 20 files attached to the assistant. Files are ordered by their creation date in ascending order.
func (o AssistantToolResourcesFileSearchOutput) VectorStoreIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v AssistantToolResourcesFileSearch) []string { return v.VectorStoreIds }).(pulumi.StringArrayOutput)
}

// Function definition for tools of type function.
func (o AssistantToolResourcesFileSearchOutput) VectorStores() AssistantToolResourcesFileSearchVectorStoresPtrOutput {
	return o.ApplyT(func(v AssistantToolResourcesFileSearch) *AssistantToolResourcesFileSearchVectorStores {
		return v.VectorStores
	}).(AssistantToolResourcesFileSearchVectorStoresPtrOutput)
}

type AssistantToolResourcesFileSearchPtrOutput struct{ *pulumi.OutputState }

func (AssistantToolResourcesFileSearchPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AssistantToolResourcesFileSearch)(nil)).Elem()
}

func (o AssistantToolResourcesFileSearchPtrOutput) ToAssistantToolResourcesFileSearchPtrOutput() AssistantToolResourcesFileSearchPtrOutput {
	return o
}

func (o AssistantToolResourcesFileSearchPtrOutput) ToAssistantToolResourcesFileSearchPtrOutputWithContext(ctx context.Context) AssistantToolResourcesFileSearchPtrOutput {
	return o
}

func (o AssistantToolResourcesFileSearchPtrOutput) Elem() AssistantToolResourcesFileSearchOutput {
	return o.ApplyT(func(v *AssistantToolResourcesFileSearch) AssistantToolResourcesFileSearch {
		if v != nil {
			return *v
		}
		var ret AssistantToolResourcesFileSearch
		return ret
	}).(AssistantToolResourcesFileSearchOutput)
}

// A list of file IDs attached to this assistant. There can be a maximum of 20 files attached to the assistant. Files are ordered by their creation date in ascending order.
func (o AssistantToolResourcesFileSearchPtrOutput) VectorStoreIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AssistantToolResourcesFileSearch) []string {
		if v == nil {
			return nil
		}
		return v.VectorStoreIds
	}).(pulumi.StringArrayOutput)
}

// Function definition for tools of type function.
func (o AssistantToolResourcesFileSearchPtrOutput) VectorStores() AssistantToolResourcesFileSearchVectorStoresPtrOutput {
	return o.ApplyT(func(v *AssistantToolResourcesFileSearch) *AssistantToolResourcesFileSearchVectorStores {
		if v == nil {
			return nil
		}
		return v.VectorStores
	}).(AssistantToolResourcesFileSearchVectorStoresPtrOutput)
}

type AssistantToolResourcesFileSearchVectorStores struct {
	// A list of file IDs attached to this assistant. There can be a maximum of 20 files attached to the assistant. Files are ordered by their creation date in ascending order.
	FileIds []string `pulumi:"fileIds"`
	// Set of 16 key-value pairs that can be attached to a vector store. This can be useful for storing additional information about the vector store in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.
	Metadata map[string]string `pulumi:"metadata"`
}

// AssistantToolResourcesFileSearchVectorStoresInput is an input type that accepts AssistantToolResourcesFileSearchVectorStoresArgs and AssistantToolResourcesFileSearchVectorStoresOutput values.
// You can construct a concrete instance of `AssistantToolResourcesFileSearchVectorStoresInput` via:
//
//	AssistantToolResourcesFileSearchVectorStoresArgs{...}
type AssistantToolResourcesFileSearchVectorStoresInput interface {
	pulumi.Input

	ToAssistantToolResourcesFileSearchVectorStoresOutput() AssistantToolResourcesFileSearchVectorStoresOutput
	ToAssistantToolResourcesFileSearchVectorStoresOutputWithContext(context.Context) AssistantToolResourcesFileSearchVectorStoresOutput
}

type AssistantToolResourcesFileSearchVectorStoresArgs struct {
	// A list of file IDs attached to this assistant. There can be a maximum of 20 files attached to the assistant. Files are ordered by their creation date in ascending order.
	FileIds pulumi.StringArrayInput `pulumi:"fileIds"`
	// Set of 16 key-value pairs that can be attached to a vector store. This can be useful for storing additional information about the vector store in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.
	Metadata pulumi.StringMapInput `pulumi:"metadata"`
}

func (AssistantToolResourcesFileSearchVectorStoresArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AssistantToolResourcesFileSearchVectorStores)(nil)).Elem()
}

func (i AssistantToolResourcesFileSearchVectorStoresArgs) ToAssistantToolResourcesFileSearchVectorStoresOutput() AssistantToolResourcesFileSearchVectorStoresOutput {
	return i.ToAssistantToolResourcesFileSearchVectorStoresOutputWithContext(context.Background())
}

func (i AssistantToolResourcesFileSearchVectorStoresArgs) ToAssistantToolResourcesFileSearchVectorStoresOutputWithContext(ctx context.Context) AssistantToolResourcesFileSearchVectorStoresOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AssistantToolResourcesFileSearchVectorStoresOutput)
}

func (i AssistantToolResourcesFileSearchVectorStoresArgs) ToAssistantToolResourcesFileSearchVectorStoresPtrOutput() AssistantToolResourcesFileSearchVectorStoresPtrOutput {
	return i.ToAssistantToolResourcesFileSearchVectorStoresPtrOutputWithContext(context.Background())
}

func (i AssistantToolResourcesFileSearchVectorStoresArgs) ToAssistantToolResourcesFileSearchVectorStoresPtrOutputWithContext(ctx context.Context) AssistantToolResourcesFileSearchVectorStoresPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AssistantToolResourcesFileSearchVectorStoresOutput).ToAssistantToolResourcesFileSearchVectorStoresPtrOutputWithContext(ctx)
}

// AssistantToolResourcesFileSearchVectorStoresPtrInput is an input type that accepts AssistantToolResourcesFileSearchVectorStoresArgs, AssistantToolResourcesFileSearchVectorStoresPtr and AssistantToolResourcesFileSearchVectorStoresPtrOutput values.
// You can construct a concrete instance of `AssistantToolResourcesFileSearchVectorStoresPtrInput` via:
//
//	        AssistantToolResourcesFileSearchVectorStoresArgs{...}
//
//	or:
//
//	        nil
type AssistantToolResourcesFileSearchVectorStoresPtrInput interface {
	pulumi.Input

	ToAssistantToolResourcesFileSearchVectorStoresPtrOutput() AssistantToolResourcesFileSearchVectorStoresPtrOutput
	ToAssistantToolResourcesFileSearchVectorStoresPtrOutputWithContext(context.Context) AssistantToolResourcesFileSearchVectorStoresPtrOutput
}

type assistantToolResourcesFileSearchVectorStoresPtrType AssistantToolResourcesFileSearchVectorStoresArgs

func AssistantToolResourcesFileSearchVectorStoresPtr(v *AssistantToolResourcesFileSearchVectorStoresArgs) AssistantToolResourcesFileSearchVectorStoresPtrInput {
	return (*assistantToolResourcesFileSearchVectorStoresPtrType)(v)
}

func (*assistantToolResourcesFileSearchVectorStoresPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**AssistantToolResourcesFileSearchVectorStores)(nil)).Elem()
}

func (i *assistantToolResourcesFileSearchVectorStoresPtrType) ToAssistantToolResourcesFileSearchVectorStoresPtrOutput() AssistantToolResourcesFileSearchVectorStoresPtrOutput {
	return i.ToAssistantToolResourcesFileSearchVectorStoresPtrOutputWithContext(context.Background())
}

func (i *assistantToolResourcesFileSearchVectorStoresPtrType) ToAssistantToolResourcesFileSearchVectorStoresPtrOutputWithContext(ctx context.Context) AssistantToolResourcesFileSearchVectorStoresPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AssistantToolResourcesFileSearchVectorStoresPtrOutput)
}

type AssistantToolResourcesFileSearchVectorStoresOutput struct{ *pulumi.OutputState }

func (AssistantToolResourcesFileSearchVectorStoresOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AssistantToolResourcesFileSearchVectorStores)(nil)).Elem()
}

func (o AssistantToolResourcesFileSearchVectorStoresOutput) ToAssistantToolResourcesFileSearchVectorStoresOutput() AssistantToolResourcesFileSearchVectorStoresOutput {
	return o
}

func (o AssistantToolResourcesFileSearchVectorStoresOutput) ToAssistantToolResourcesFileSearchVectorStoresOutputWithContext(ctx context.Context) AssistantToolResourcesFileSearchVectorStoresOutput {
	return o
}

func (o AssistantToolResourcesFileSearchVectorStoresOutput) ToAssistantToolResourcesFileSearchVectorStoresPtrOutput() AssistantToolResourcesFileSearchVectorStoresPtrOutput {
	return o.ToAssistantToolResourcesFileSearchVectorStoresPtrOutputWithContext(context.Background())
}

func (o AssistantToolResourcesFileSearchVectorStoresOutput) ToAssistantToolResourcesFileSearchVectorStoresPtrOutputWithContext(ctx context.Context) AssistantToolResourcesFileSearchVectorStoresPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v AssistantToolResourcesFileSearchVectorStores) *AssistantToolResourcesFileSearchVectorStores {
		return &v
	}).(AssistantToolResourcesFileSearchVectorStoresPtrOutput)
}

// A list of file IDs attached to this assistant. There can be a maximum of 20 files attached to the assistant. Files are ordered by their creation date in ascending order.
func (o AssistantToolResourcesFileSearchVectorStoresOutput) FileIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v AssistantToolResourcesFileSearchVectorStores) []string { return v.FileIds }).(pulumi.StringArrayOutput)
}

// Set of 16 key-value pairs that can be attached to a vector store. This can be useful for storing additional information about the vector store in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.
func (o AssistantToolResourcesFileSearchVectorStoresOutput) Metadata() pulumi.StringMapOutput {
	return o.ApplyT(func(v AssistantToolResourcesFileSearchVectorStores) map[string]string { return v.Metadata }).(pulumi.StringMapOutput)
}

type AssistantToolResourcesFileSearchVectorStoresPtrOutput struct{ *pulumi.OutputState }

func (AssistantToolResourcesFileSearchVectorStoresPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AssistantToolResourcesFileSearchVectorStores)(nil)).Elem()
}

func (o AssistantToolResourcesFileSearchVectorStoresPtrOutput) ToAssistantToolResourcesFileSearchVectorStoresPtrOutput() AssistantToolResourcesFileSearchVectorStoresPtrOutput {
	return o
}

func (o AssistantToolResourcesFileSearchVectorStoresPtrOutput) ToAssistantToolResourcesFileSearchVectorStoresPtrOutputWithContext(ctx context.Context) AssistantToolResourcesFileSearchVectorStoresPtrOutput {
	return o
}

func (o AssistantToolResourcesFileSearchVectorStoresPtrOutput) Elem() AssistantToolResourcesFileSearchVectorStoresOutput {
	return o.ApplyT(func(v *AssistantToolResourcesFileSearchVectorStores) AssistantToolResourcesFileSearchVectorStores {
		if v != nil {
			return *v
		}
		var ret AssistantToolResourcesFileSearchVectorStores
		return ret
	}).(AssistantToolResourcesFileSearchVectorStoresOutput)
}

// A list of file IDs attached to this assistant. There can be a maximum of 20 files attached to the assistant. Files are ordered by their creation date in ascending order.
func (o AssistantToolResourcesFileSearchVectorStoresPtrOutput) FileIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *AssistantToolResourcesFileSearchVectorStores) []string {
		if v == nil {
			return nil
		}
		return v.FileIds
	}).(pulumi.StringArrayOutput)
}

// Set of 16 key-value pairs that can be attached to a vector store. This can be useful for storing additional information about the vector store in a structured format. Keys can be a maximum of 64 characters long and values can be a maxium of 512 characters long.
func (o AssistantToolResourcesFileSearchVectorStoresPtrOutput) Metadata() pulumi.StringMapOutput {
	return o.ApplyT(func(v *AssistantToolResourcesFileSearchVectorStores) map[string]string {
		if v == nil {
			return nil
		}
		return v.Metadata
	}).(pulumi.StringMapOutput)
}

type FinetuningJobHyperparams struct {
	// N Epochs
	NEpochs *int `pulumi:"nEpochs"`
}

// FinetuningJobHyperparamsInput is an input type that accepts FinetuningJobHyperparamsArgs and FinetuningJobHyperparamsOutput values.
// You can construct a concrete instance of `FinetuningJobHyperparamsInput` via:
//
//	FinetuningJobHyperparamsArgs{...}
type FinetuningJobHyperparamsInput interface {
	pulumi.Input

	ToFinetuningJobHyperparamsOutput() FinetuningJobHyperparamsOutput
	ToFinetuningJobHyperparamsOutputWithContext(context.Context) FinetuningJobHyperparamsOutput
}

type FinetuningJobHyperparamsArgs struct {
	// N Epochs
	NEpochs pulumi.IntPtrInput `pulumi:"nEpochs"`
}

func (FinetuningJobHyperparamsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*FinetuningJobHyperparams)(nil)).Elem()
}

func (i FinetuningJobHyperparamsArgs) ToFinetuningJobHyperparamsOutput() FinetuningJobHyperparamsOutput {
	return i.ToFinetuningJobHyperparamsOutputWithContext(context.Background())
}

func (i FinetuningJobHyperparamsArgs) ToFinetuningJobHyperparamsOutputWithContext(ctx context.Context) FinetuningJobHyperparamsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FinetuningJobHyperparamsOutput)
}

func (i FinetuningJobHyperparamsArgs) ToFinetuningJobHyperparamsPtrOutput() FinetuningJobHyperparamsPtrOutput {
	return i.ToFinetuningJobHyperparamsPtrOutputWithContext(context.Background())
}

func (i FinetuningJobHyperparamsArgs) ToFinetuningJobHyperparamsPtrOutputWithContext(ctx context.Context) FinetuningJobHyperparamsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FinetuningJobHyperparamsOutput).ToFinetuningJobHyperparamsPtrOutputWithContext(ctx)
}

// FinetuningJobHyperparamsPtrInput is an input type that accepts FinetuningJobHyperparamsArgs, FinetuningJobHyperparamsPtr and FinetuningJobHyperparamsPtrOutput values.
// You can construct a concrete instance of `FinetuningJobHyperparamsPtrInput` via:
//
//	        FinetuningJobHyperparamsArgs{...}
//
//	or:
//
//	        nil
type FinetuningJobHyperparamsPtrInput interface {
	pulumi.Input

	ToFinetuningJobHyperparamsPtrOutput() FinetuningJobHyperparamsPtrOutput
	ToFinetuningJobHyperparamsPtrOutputWithContext(context.Context) FinetuningJobHyperparamsPtrOutput
}

type finetuningJobHyperparamsPtrType FinetuningJobHyperparamsArgs

func FinetuningJobHyperparamsPtr(v *FinetuningJobHyperparamsArgs) FinetuningJobHyperparamsPtrInput {
	return (*finetuningJobHyperparamsPtrType)(v)
}

func (*finetuningJobHyperparamsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**FinetuningJobHyperparams)(nil)).Elem()
}

func (i *finetuningJobHyperparamsPtrType) ToFinetuningJobHyperparamsPtrOutput() FinetuningJobHyperparamsPtrOutput {
	return i.ToFinetuningJobHyperparamsPtrOutputWithContext(context.Background())
}

func (i *finetuningJobHyperparamsPtrType) ToFinetuningJobHyperparamsPtrOutputWithContext(ctx context.Context) FinetuningJobHyperparamsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FinetuningJobHyperparamsPtrOutput)
}

type FinetuningJobHyperparamsOutput struct{ *pulumi.OutputState }

func (FinetuningJobHyperparamsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*FinetuningJobHyperparams)(nil)).Elem()
}

func (o FinetuningJobHyperparamsOutput) ToFinetuningJobHyperparamsOutput() FinetuningJobHyperparamsOutput {
	return o
}

func (o FinetuningJobHyperparamsOutput) ToFinetuningJobHyperparamsOutputWithContext(ctx context.Context) FinetuningJobHyperparamsOutput {
	return o
}

func (o FinetuningJobHyperparamsOutput) ToFinetuningJobHyperparamsPtrOutput() FinetuningJobHyperparamsPtrOutput {
	return o.ToFinetuningJobHyperparamsPtrOutputWithContext(context.Background())
}

func (o FinetuningJobHyperparamsOutput) ToFinetuningJobHyperparamsPtrOutputWithContext(ctx context.Context) FinetuningJobHyperparamsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v FinetuningJobHyperparams) *FinetuningJobHyperparams {
		return &v
	}).(FinetuningJobHyperparamsPtrOutput)
}

// N Epochs
func (o FinetuningJobHyperparamsOutput) NEpochs() pulumi.IntPtrOutput {
	return o.ApplyT(func(v FinetuningJobHyperparams) *int { return v.NEpochs }).(pulumi.IntPtrOutput)
}

type FinetuningJobHyperparamsPtrOutput struct{ *pulumi.OutputState }

func (FinetuningJobHyperparamsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FinetuningJobHyperparams)(nil)).Elem()
}

func (o FinetuningJobHyperparamsPtrOutput) ToFinetuningJobHyperparamsPtrOutput() FinetuningJobHyperparamsPtrOutput {
	return o
}

func (o FinetuningJobHyperparamsPtrOutput) ToFinetuningJobHyperparamsPtrOutputWithContext(ctx context.Context) FinetuningJobHyperparamsPtrOutput {
	return o
}

func (o FinetuningJobHyperparamsPtrOutput) Elem() FinetuningJobHyperparamsOutput {
	return o.ApplyT(func(v *FinetuningJobHyperparams) FinetuningJobHyperparams {
		if v != nil {
			return *v
		}
		var ret FinetuningJobHyperparams
		return ret
	}).(FinetuningJobHyperparamsOutput)
}

// N Epochs
func (o FinetuningJobHyperparamsPtrOutput) NEpochs() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *FinetuningJobHyperparams) *int {
		if v == nil {
			return nil
		}
		return v.NEpochs
	}).(pulumi.IntPtrOutput)
}

type GetFilesFile struct {
	// File size in bytes
	Bytes int `pulumi:"bytes"`
	// Created Time
	Created int `pulumi:"created"`
	// Filename
	Filename string `pulumi:"filename"`
	// Filepath
	Filepath string `pulumi:"filepath"`
	// File Identifier
	Id string `pulumi:"id"`
	// Object Type
	Object string `pulumi:"object"`
	// Intended use of file. Use 'fine-tune' for Fine-tuning
	Purpose string `pulumi:"purpose"`
}

// GetFilesFileInput is an input type that accepts GetFilesFileArgs and GetFilesFileOutput values.
// You can construct a concrete instance of `GetFilesFileInput` via:
//
//	GetFilesFileArgs{...}
type GetFilesFileInput interface {
	pulumi.Input

	ToGetFilesFileOutput() GetFilesFileOutput
	ToGetFilesFileOutputWithContext(context.Context) GetFilesFileOutput
}

type GetFilesFileArgs struct {
	// File size in bytes
	Bytes pulumi.IntInput `pulumi:"bytes"`
	// Created Time
	Created pulumi.IntInput `pulumi:"created"`
	// Filename
	Filename pulumi.StringInput `pulumi:"filename"`
	// Filepath
	Filepath pulumi.StringInput `pulumi:"filepath"`
	// File Identifier
	Id pulumi.StringInput `pulumi:"id"`
	// Object Type
	Object pulumi.StringInput `pulumi:"object"`
	// Intended use of file. Use 'fine-tune' for Fine-tuning
	Purpose pulumi.StringInput `pulumi:"purpose"`
}

func (GetFilesFileArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFilesFile)(nil)).Elem()
}

func (i GetFilesFileArgs) ToGetFilesFileOutput() GetFilesFileOutput {
	return i.ToGetFilesFileOutputWithContext(context.Background())
}

func (i GetFilesFileArgs) ToGetFilesFileOutputWithContext(ctx context.Context) GetFilesFileOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetFilesFileOutput)
}

// GetFilesFileArrayInput is an input type that accepts GetFilesFileArray and GetFilesFileArrayOutput values.
// You can construct a concrete instance of `GetFilesFileArrayInput` via:
//
//	GetFilesFileArray{ GetFilesFileArgs{...} }
type GetFilesFileArrayInput interface {
	pulumi.Input

	ToGetFilesFileArrayOutput() GetFilesFileArrayOutput
	ToGetFilesFileArrayOutputWithContext(context.Context) GetFilesFileArrayOutput
}

type GetFilesFileArray []GetFilesFileInput

func (GetFilesFileArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetFilesFile)(nil)).Elem()
}

func (i GetFilesFileArray) ToGetFilesFileArrayOutput() GetFilesFileArrayOutput {
	return i.ToGetFilesFileArrayOutputWithContext(context.Background())
}

func (i GetFilesFileArray) ToGetFilesFileArrayOutputWithContext(ctx context.Context) GetFilesFileArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetFilesFileArrayOutput)
}

type GetFilesFileOutput struct{ *pulumi.OutputState }

func (GetFilesFileOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFilesFile)(nil)).Elem()
}

func (o GetFilesFileOutput) ToGetFilesFileOutput() GetFilesFileOutput {
	return o
}

func (o GetFilesFileOutput) ToGetFilesFileOutputWithContext(ctx context.Context) GetFilesFileOutput {
	return o
}

// File size in bytes
func (o GetFilesFileOutput) Bytes() pulumi.IntOutput {
	return o.ApplyT(func(v GetFilesFile) int { return v.Bytes }).(pulumi.IntOutput)
}

// Created Time
func (o GetFilesFileOutput) Created() pulumi.IntOutput {
	return o.ApplyT(func(v GetFilesFile) int { return v.Created }).(pulumi.IntOutput)
}

// Filename
func (o GetFilesFileOutput) Filename() pulumi.StringOutput {
	return o.ApplyT(func(v GetFilesFile) string { return v.Filename }).(pulumi.StringOutput)
}

// Filepath
func (o GetFilesFileOutput) Filepath() pulumi.StringOutput {
	return o.ApplyT(func(v GetFilesFile) string { return v.Filepath }).(pulumi.StringOutput)
}

// File Identifier
func (o GetFilesFileOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetFilesFile) string { return v.Id }).(pulumi.StringOutput)
}

// Object Type
func (o GetFilesFileOutput) Object() pulumi.StringOutput {
	return o.ApplyT(func(v GetFilesFile) string { return v.Object }).(pulumi.StringOutput)
}

// Intended use of file. Use 'fine-tune' for Fine-tuning
func (o GetFilesFileOutput) Purpose() pulumi.StringOutput {
	return o.ApplyT(func(v GetFilesFile) string { return v.Purpose }).(pulumi.StringOutput)
}

type GetFilesFileArrayOutput struct{ *pulumi.OutputState }

func (GetFilesFileArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetFilesFile)(nil)).Elem()
}

func (o GetFilesFileArrayOutput) ToGetFilesFileArrayOutput() GetFilesFileArrayOutput {
	return o
}

func (o GetFilesFileArrayOutput) ToGetFilesFileArrayOutputWithContext(ctx context.Context) GetFilesFileArrayOutput {
	return o
}

func (o GetFilesFileArrayOutput) Index(i pulumi.IntInput) GetFilesFileOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetFilesFile {
		return vs[0].([]GetFilesFile)[vs[1].(int)]
	}).(GetFilesFileOutput)
}

type GetFinetuningJobHyperparams struct {
	// N Epochs
	NEpochs int `pulumi:"nEpochs"`
}

// GetFinetuningJobHyperparamsInput is an input type that accepts GetFinetuningJobHyperparamsArgs and GetFinetuningJobHyperparamsOutput values.
// You can construct a concrete instance of `GetFinetuningJobHyperparamsInput` via:
//
//	GetFinetuningJobHyperparamsArgs{...}
type GetFinetuningJobHyperparamsInput interface {
	pulumi.Input

	ToGetFinetuningJobHyperparamsOutput() GetFinetuningJobHyperparamsOutput
	ToGetFinetuningJobHyperparamsOutputWithContext(context.Context) GetFinetuningJobHyperparamsOutput
}

type GetFinetuningJobHyperparamsArgs struct {
	// N Epochs
	NEpochs pulumi.IntInput `pulumi:"nEpochs"`
}

func (GetFinetuningJobHyperparamsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFinetuningJobHyperparams)(nil)).Elem()
}

func (i GetFinetuningJobHyperparamsArgs) ToGetFinetuningJobHyperparamsOutput() GetFinetuningJobHyperparamsOutput {
	return i.ToGetFinetuningJobHyperparamsOutputWithContext(context.Background())
}

func (i GetFinetuningJobHyperparamsArgs) ToGetFinetuningJobHyperparamsOutputWithContext(ctx context.Context) GetFinetuningJobHyperparamsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetFinetuningJobHyperparamsOutput)
}

type GetFinetuningJobHyperparamsOutput struct{ *pulumi.OutputState }

func (GetFinetuningJobHyperparamsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFinetuningJobHyperparams)(nil)).Elem()
}

func (o GetFinetuningJobHyperparamsOutput) ToGetFinetuningJobHyperparamsOutput() GetFinetuningJobHyperparamsOutput {
	return o
}

func (o GetFinetuningJobHyperparamsOutput) ToGetFinetuningJobHyperparamsOutputWithContext(ctx context.Context) GetFinetuningJobHyperparamsOutput {
	return o
}

// N Epochs
func (o GetFinetuningJobHyperparamsOutput) NEpochs() pulumi.IntOutput {
	return o.ApplyT(func(v GetFinetuningJobHyperparams) int { return v.NEpochs }).(pulumi.IntOutput)
}

type GetFinetuningJobsJob struct {
	// Created Time
	CreatedAt int `pulumi:"createdAt"`
	// Fine-Tuned Model ID
	FineTunedModel string `pulumi:"fineTunedModel"`
	// Finished Time
	FinishedAt int `pulumi:"finishedAt"`
	// Hyperparams
	Hyperparams GetFinetuningJobsJobHyperparams `pulumi:"hyperparams"`
	// Fine-Tuning Job Identifier
	Id string `pulumi:"id"`
	// Model ID
	Model string `pulumi:"model"`
	// Object Type
	Object string `pulumi:"object"`
	// Organization ID
	OrganizationId string `pulumi:"organizationId"`
	// Result Files
	ResultFiles []string `pulumi:"resultFiles"`
	// Status
	Status string `pulumi:"status"`
	// Trained Tokens
	TrainedTokens int `pulumi:"trainedTokens"`
	// Training File
	TrainingFile string `pulumi:"trainingFile"`
	// Validation File
	ValidationFile string `pulumi:"validationFile"`
}

// GetFinetuningJobsJobInput is an input type that accepts GetFinetuningJobsJobArgs and GetFinetuningJobsJobOutput values.
// You can construct a concrete instance of `GetFinetuningJobsJobInput` via:
//
//	GetFinetuningJobsJobArgs{...}
type GetFinetuningJobsJobInput interface {
	pulumi.Input

	ToGetFinetuningJobsJobOutput() GetFinetuningJobsJobOutput
	ToGetFinetuningJobsJobOutputWithContext(context.Context) GetFinetuningJobsJobOutput
}

type GetFinetuningJobsJobArgs struct {
	// Created Time
	CreatedAt pulumi.IntInput `pulumi:"createdAt"`
	// Fine-Tuned Model ID
	FineTunedModel pulumi.StringInput `pulumi:"fineTunedModel"`
	// Finished Time
	FinishedAt pulumi.IntInput `pulumi:"finishedAt"`
	// Hyperparams
	Hyperparams GetFinetuningJobsJobHyperparamsInput `pulumi:"hyperparams"`
	// Fine-Tuning Job Identifier
	Id pulumi.StringInput `pulumi:"id"`
	// Model ID
	Model pulumi.StringInput `pulumi:"model"`
	// Object Type
	Object pulumi.StringInput `pulumi:"object"`
	// Organization ID
	OrganizationId pulumi.StringInput `pulumi:"organizationId"`
	// Result Files
	ResultFiles pulumi.StringArrayInput `pulumi:"resultFiles"`
	// Status
	Status pulumi.StringInput `pulumi:"status"`
	// Trained Tokens
	TrainedTokens pulumi.IntInput `pulumi:"trainedTokens"`
	// Training File
	TrainingFile pulumi.StringInput `pulumi:"trainingFile"`
	// Validation File
	ValidationFile pulumi.StringInput `pulumi:"validationFile"`
}

func (GetFinetuningJobsJobArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFinetuningJobsJob)(nil)).Elem()
}

func (i GetFinetuningJobsJobArgs) ToGetFinetuningJobsJobOutput() GetFinetuningJobsJobOutput {
	return i.ToGetFinetuningJobsJobOutputWithContext(context.Background())
}

func (i GetFinetuningJobsJobArgs) ToGetFinetuningJobsJobOutputWithContext(ctx context.Context) GetFinetuningJobsJobOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetFinetuningJobsJobOutput)
}

// GetFinetuningJobsJobArrayInput is an input type that accepts GetFinetuningJobsJobArray and GetFinetuningJobsJobArrayOutput values.
// You can construct a concrete instance of `GetFinetuningJobsJobArrayInput` via:
//
//	GetFinetuningJobsJobArray{ GetFinetuningJobsJobArgs{...} }
type GetFinetuningJobsJobArrayInput interface {
	pulumi.Input

	ToGetFinetuningJobsJobArrayOutput() GetFinetuningJobsJobArrayOutput
	ToGetFinetuningJobsJobArrayOutputWithContext(context.Context) GetFinetuningJobsJobArrayOutput
}

type GetFinetuningJobsJobArray []GetFinetuningJobsJobInput

func (GetFinetuningJobsJobArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetFinetuningJobsJob)(nil)).Elem()
}

func (i GetFinetuningJobsJobArray) ToGetFinetuningJobsJobArrayOutput() GetFinetuningJobsJobArrayOutput {
	return i.ToGetFinetuningJobsJobArrayOutputWithContext(context.Background())
}

func (i GetFinetuningJobsJobArray) ToGetFinetuningJobsJobArrayOutputWithContext(ctx context.Context) GetFinetuningJobsJobArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetFinetuningJobsJobArrayOutput)
}

type GetFinetuningJobsJobOutput struct{ *pulumi.OutputState }

func (GetFinetuningJobsJobOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFinetuningJobsJob)(nil)).Elem()
}

func (o GetFinetuningJobsJobOutput) ToGetFinetuningJobsJobOutput() GetFinetuningJobsJobOutput {
	return o
}

func (o GetFinetuningJobsJobOutput) ToGetFinetuningJobsJobOutputWithContext(ctx context.Context) GetFinetuningJobsJobOutput {
	return o
}

// Created Time
func (o GetFinetuningJobsJobOutput) CreatedAt() pulumi.IntOutput {
	return o.ApplyT(func(v GetFinetuningJobsJob) int { return v.CreatedAt }).(pulumi.IntOutput)
}

// Fine-Tuned Model ID
func (o GetFinetuningJobsJobOutput) FineTunedModel() pulumi.StringOutput {
	return o.ApplyT(func(v GetFinetuningJobsJob) string { return v.FineTunedModel }).(pulumi.StringOutput)
}

// Finished Time
func (o GetFinetuningJobsJobOutput) FinishedAt() pulumi.IntOutput {
	return o.ApplyT(func(v GetFinetuningJobsJob) int { return v.FinishedAt }).(pulumi.IntOutput)
}

// Hyperparams
func (o GetFinetuningJobsJobOutput) Hyperparams() GetFinetuningJobsJobHyperparamsOutput {
	return o.ApplyT(func(v GetFinetuningJobsJob) GetFinetuningJobsJobHyperparams { return v.Hyperparams }).(GetFinetuningJobsJobHyperparamsOutput)
}

// Fine-Tuning Job Identifier
func (o GetFinetuningJobsJobOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetFinetuningJobsJob) string { return v.Id }).(pulumi.StringOutput)
}

// Model ID
func (o GetFinetuningJobsJobOutput) Model() pulumi.StringOutput {
	return o.ApplyT(func(v GetFinetuningJobsJob) string { return v.Model }).(pulumi.StringOutput)
}

// Object Type
func (o GetFinetuningJobsJobOutput) Object() pulumi.StringOutput {
	return o.ApplyT(func(v GetFinetuningJobsJob) string { return v.Object }).(pulumi.StringOutput)
}

// Organization ID
func (o GetFinetuningJobsJobOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v GetFinetuningJobsJob) string { return v.OrganizationId }).(pulumi.StringOutput)
}

// Result Files
func (o GetFinetuningJobsJobOutput) ResultFiles() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetFinetuningJobsJob) []string { return v.ResultFiles }).(pulumi.StringArrayOutput)
}

// Status
func (o GetFinetuningJobsJobOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetFinetuningJobsJob) string { return v.Status }).(pulumi.StringOutput)
}

// Trained Tokens
func (o GetFinetuningJobsJobOutput) TrainedTokens() pulumi.IntOutput {
	return o.ApplyT(func(v GetFinetuningJobsJob) int { return v.TrainedTokens }).(pulumi.IntOutput)
}

// Training File
func (o GetFinetuningJobsJobOutput) TrainingFile() pulumi.StringOutput {
	return o.ApplyT(func(v GetFinetuningJobsJob) string { return v.TrainingFile }).(pulumi.StringOutput)
}

// Validation File
func (o GetFinetuningJobsJobOutput) ValidationFile() pulumi.StringOutput {
	return o.ApplyT(func(v GetFinetuningJobsJob) string { return v.ValidationFile }).(pulumi.StringOutput)
}

type GetFinetuningJobsJobArrayOutput struct{ *pulumi.OutputState }

func (GetFinetuningJobsJobArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetFinetuningJobsJob)(nil)).Elem()
}

func (o GetFinetuningJobsJobArrayOutput) ToGetFinetuningJobsJobArrayOutput() GetFinetuningJobsJobArrayOutput {
	return o
}

func (o GetFinetuningJobsJobArrayOutput) ToGetFinetuningJobsJobArrayOutputWithContext(ctx context.Context) GetFinetuningJobsJobArrayOutput {
	return o
}

func (o GetFinetuningJobsJobArrayOutput) Index(i pulumi.IntInput) GetFinetuningJobsJobOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetFinetuningJobsJob {
		return vs[0].([]GetFinetuningJobsJob)[vs[1].(int)]
	}).(GetFinetuningJobsJobOutput)
}

type GetFinetuningJobsJobHyperparams struct {
	// N Epochs
	NEpochs int `pulumi:"nEpochs"`
}

// GetFinetuningJobsJobHyperparamsInput is an input type that accepts GetFinetuningJobsJobHyperparamsArgs and GetFinetuningJobsJobHyperparamsOutput values.
// You can construct a concrete instance of `GetFinetuningJobsJobHyperparamsInput` via:
//
//	GetFinetuningJobsJobHyperparamsArgs{...}
type GetFinetuningJobsJobHyperparamsInput interface {
	pulumi.Input

	ToGetFinetuningJobsJobHyperparamsOutput() GetFinetuningJobsJobHyperparamsOutput
	ToGetFinetuningJobsJobHyperparamsOutputWithContext(context.Context) GetFinetuningJobsJobHyperparamsOutput
}

type GetFinetuningJobsJobHyperparamsArgs struct {
	// N Epochs
	NEpochs pulumi.IntInput `pulumi:"nEpochs"`
}

func (GetFinetuningJobsJobHyperparamsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFinetuningJobsJobHyperparams)(nil)).Elem()
}

func (i GetFinetuningJobsJobHyperparamsArgs) ToGetFinetuningJobsJobHyperparamsOutput() GetFinetuningJobsJobHyperparamsOutput {
	return i.ToGetFinetuningJobsJobHyperparamsOutputWithContext(context.Background())
}

func (i GetFinetuningJobsJobHyperparamsArgs) ToGetFinetuningJobsJobHyperparamsOutputWithContext(ctx context.Context) GetFinetuningJobsJobHyperparamsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetFinetuningJobsJobHyperparamsOutput)
}

type GetFinetuningJobsJobHyperparamsOutput struct{ *pulumi.OutputState }

func (GetFinetuningJobsJobHyperparamsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetFinetuningJobsJobHyperparams)(nil)).Elem()
}

func (o GetFinetuningJobsJobHyperparamsOutput) ToGetFinetuningJobsJobHyperparamsOutput() GetFinetuningJobsJobHyperparamsOutput {
	return o
}

func (o GetFinetuningJobsJobHyperparamsOutput) ToGetFinetuningJobsJobHyperparamsOutputWithContext(ctx context.Context) GetFinetuningJobsJobHyperparamsOutput {
	return o
}

// N Epochs
func (o GetFinetuningJobsJobHyperparamsOutput) NEpochs() pulumi.IntOutput {
	return o.ApplyT(func(v GetFinetuningJobsJobHyperparams) int { return v.NEpochs }).(pulumi.IntOutput)
}

type GetModelPermission struct {
	// Allow Create Engine
	AllowCreateEngine bool `pulumi:"allowCreateEngine"`
	// Allow Fine Tuning
	AllowFineTuning bool `pulumi:"allowFineTuning"`
	// Allow Logprobs
	AllowLogprobs bool `pulumi:"allowLogprobs"`
	// Allow Sampling
	AllowSampling bool `pulumi:"allowSampling"`
	// Allow Search Indices
	AllowSearchIndices bool `pulumi:"allowSearchIndices"`
	// Allow View
	AllowView bool `pulumi:"allowView"`
	// Created Time
	Created int `pulumi:"created"`
	// Permission Identifier
	Id string `pulumi:"id"`
	// Is Blocking
	IsBlocking bool `pulumi:"isBlocking"`
	// Object Type
	Object string `pulumi:"object"`
	// Organization
	Organization string `pulumi:"organization"`
}

// GetModelPermissionInput is an input type that accepts GetModelPermissionArgs and GetModelPermissionOutput values.
// You can construct a concrete instance of `GetModelPermissionInput` via:
//
//	GetModelPermissionArgs{...}
type GetModelPermissionInput interface {
	pulumi.Input

	ToGetModelPermissionOutput() GetModelPermissionOutput
	ToGetModelPermissionOutputWithContext(context.Context) GetModelPermissionOutput
}

type GetModelPermissionArgs struct {
	// Allow Create Engine
	AllowCreateEngine pulumi.BoolInput `pulumi:"allowCreateEngine"`
	// Allow Fine Tuning
	AllowFineTuning pulumi.BoolInput `pulumi:"allowFineTuning"`
	// Allow Logprobs
	AllowLogprobs pulumi.BoolInput `pulumi:"allowLogprobs"`
	// Allow Sampling
	AllowSampling pulumi.BoolInput `pulumi:"allowSampling"`
	// Allow Search Indices
	AllowSearchIndices pulumi.BoolInput `pulumi:"allowSearchIndices"`
	// Allow View
	AllowView pulumi.BoolInput `pulumi:"allowView"`
	// Created Time
	Created pulumi.IntInput `pulumi:"created"`
	// Permission Identifier
	Id pulumi.StringInput `pulumi:"id"`
	// Is Blocking
	IsBlocking pulumi.BoolInput `pulumi:"isBlocking"`
	// Object Type
	Object pulumi.StringInput `pulumi:"object"`
	// Organization
	Organization pulumi.StringInput `pulumi:"organization"`
}

func (GetModelPermissionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetModelPermission)(nil)).Elem()
}

func (i GetModelPermissionArgs) ToGetModelPermissionOutput() GetModelPermissionOutput {
	return i.ToGetModelPermissionOutputWithContext(context.Background())
}

func (i GetModelPermissionArgs) ToGetModelPermissionOutputWithContext(ctx context.Context) GetModelPermissionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetModelPermissionOutput)
}

// GetModelPermissionArrayInput is an input type that accepts GetModelPermissionArray and GetModelPermissionArrayOutput values.
// You can construct a concrete instance of `GetModelPermissionArrayInput` via:
//
//	GetModelPermissionArray{ GetModelPermissionArgs{...} }
type GetModelPermissionArrayInput interface {
	pulumi.Input

	ToGetModelPermissionArrayOutput() GetModelPermissionArrayOutput
	ToGetModelPermissionArrayOutputWithContext(context.Context) GetModelPermissionArrayOutput
}

type GetModelPermissionArray []GetModelPermissionInput

func (GetModelPermissionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetModelPermission)(nil)).Elem()
}

func (i GetModelPermissionArray) ToGetModelPermissionArrayOutput() GetModelPermissionArrayOutput {
	return i.ToGetModelPermissionArrayOutputWithContext(context.Background())
}

func (i GetModelPermissionArray) ToGetModelPermissionArrayOutputWithContext(ctx context.Context) GetModelPermissionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetModelPermissionArrayOutput)
}

type GetModelPermissionOutput struct{ *pulumi.OutputState }

func (GetModelPermissionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetModelPermission)(nil)).Elem()
}

func (o GetModelPermissionOutput) ToGetModelPermissionOutput() GetModelPermissionOutput {
	return o
}

func (o GetModelPermissionOutput) ToGetModelPermissionOutputWithContext(ctx context.Context) GetModelPermissionOutput {
	return o
}

// Allow Create Engine
func (o GetModelPermissionOutput) AllowCreateEngine() pulumi.BoolOutput {
	return o.ApplyT(func(v GetModelPermission) bool { return v.AllowCreateEngine }).(pulumi.BoolOutput)
}

// Allow Fine Tuning
func (o GetModelPermissionOutput) AllowFineTuning() pulumi.BoolOutput {
	return o.ApplyT(func(v GetModelPermission) bool { return v.AllowFineTuning }).(pulumi.BoolOutput)
}

// Allow Logprobs
func (o GetModelPermissionOutput) AllowLogprobs() pulumi.BoolOutput {
	return o.ApplyT(func(v GetModelPermission) bool { return v.AllowLogprobs }).(pulumi.BoolOutput)
}

// Allow Sampling
func (o GetModelPermissionOutput) AllowSampling() pulumi.BoolOutput {
	return o.ApplyT(func(v GetModelPermission) bool { return v.AllowSampling }).(pulumi.BoolOutput)
}

// Allow Search Indices
func (o GetModelPermissionOutput) AllowSearchIndices() pulumi.BoolOutput {
	return o.ApplyT(func(v GetModelPermission) bool { return v.AllowSearchIndices }).(pulumi.BoolOutput)
}

// Allow View
func (o GetModelPermissionOutput) AllowView() pulumi.BoolOutput {
	return o.ApplyT(func(v GetModelPermission) bool { return v.AllowView }).(pulumi.BoolOutput)
}

// Created Time
func (o GetModelPermissionOutput) Created() pulumi.IntOutput {
	return o.ApplyT(func(v GetModelPermission) int { return v.Created }).(pulumi.IntOutput)
}

// Permission Identifier
func (o GetModelPermissionOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelPermission) string { return v.Id }).(pulumi.StringOutput)
}

// Is Blocking
func (o GetModelPermissionOutput) IsBlocking() pulumi.BoolOutput {
	return o.ApplyT(func(v GetModelPermission) bool { return v.IsBlocking }).(pulumi.BoolOutput)
}

// Object Type
func (o GetModelPermissionOutput) Object() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelPermission) string { return v.Object }).(pulumi.StringOutput)
}

// Organization
func (o GetModelPermissionOutput) Organization() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelPermission) string { return v.Organization }).(pulumi.StringOutput)
}

type GetModelPermissionArrayOutput struct{ *pulumi.OutputState }

func (GetModelPermissionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetModelPermission)(nil)).Elem()
}

func (o GetModelPermissionArrayOutput) ToGetModelPermissionArrayOutput() GetModelPermissionArrayOutput {
	return o
}

func (o GetModelPermissionArrayOutput) ToGetModelPermissionArrayOutputWithContext(ctx context.Context) GetModelPermissionArrayOutput {
	return o
}

func (o GetModelPermissionArrayOutput) Index(i pulumi.IntInput) GetModelPermissionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetModelPermission {
		return vs[0].([]GetModelPermission)[vs[1].(int)]
	}).(GetModelPermissionOutput)
}

type GetModelsModel struct {
	// Created Time
	Created int `pulumi:"created"`
	// Model Identifier
	Id string `pulumi:"id"`
	// Object Type
	Object string `pulumi:"object"`
	// Model Owner
	OwnedBy string `pulumi:"ownedBy"`
	// Parent
	Parent string `pulumi:"parent"`
	// Permissions
	Permissions []GetModelsModelPermission `pulumi:"permissions"`
	// Root
	Root string `pulumi:"root"`
}

// GetModelsModelInput is an input type that accepts GetModelsModelArgs and GetModelsModelOutput values.
// You can construct a concrete instance of `GetModelsModelInput` via:
//
//	GetModelsModelArgs{...}
type GetModelsModelInput interface {
	pulumi.Input

	ToGetModelsModelOutput() GetModelsModelOutput
	ToGetModelsModelOutputWithContext(context.Context) GetModelsModelOutput
}

type GetModelsModelArgs struct {
	// Created Time
	Created pulumi.IntInput `pulumi:"created"`
	// Model Identifier
	Id pulumi.StringInput `pulumi:"id"`
	// Object Type
	Object pulumi.StringInput `pulumi:"object"`
	// Model Owner
	OwnedBy pulumi.StringInput `pulumi:"ownedBy"`
	// Parent
	Parent pulumi.StringInput `pulumi:"parent"`
	// Permissions
	Permissions GetModelsModelPermissionArrayInput `pulumi:"permissions"`
	// Root
	Root pulumi.StringInput `pulumi:"root"`
}

func (GetModelsModelArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetModelsModel)(nil)).Elem()
}

func (i GetModelsModelArgs) ToGetModelsModelOutput() GetModelsModelOutput {
	return i.ToGetModelsModelOutputWithContext(context.Background())
}

func (i GetModelsModelArgs) ToGetModelsModelOutputWithContext(ctx context.Context) GetModelsModelOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetModelsModelOutput)
}

// GetModelsModelArrayInput is an input type that accepts GetModelsModelArray and GetModelsModelArrayOutput values.
// You can construct a concrete instance of `GetModelsModelArrayInput` via:
//
//	GetModelsModelArray{ GetModelsModelArgs{...} }
type GetModelsModelArrayInput interface {
	pulumi.Input

	ToGetModelsModelArrayOutput() GetModelsModelArrayOutput
	ToGetModelsModelArrayOutputWithContext(context.Context) GetModelsModelArrayOutput
}

type GetModelsModelArray []GetModelsModelInput

func (GetModelsModelArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetModelsModel)(nil)).Elem()
}

func (i GetModelsModelArray) ToGetModelsModelArrayOutput() GetModelsModelArrayOutput {
	return i.ToGetModelsModelArrayOutputWithContext(context.Background())
}

func (i GetModelsModelArray) ToGetModelsModelArrayOutputWithContext(ctx context.Context) GetModelsModelArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetModelsModelArrayOutput)
}

type GetModelsModelOutput struct{ *pulumi.OutputState }

func (GetModelsModelOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetModelsModel)(nil)).Elem()
}

func (o GetModelsModelOutput) ToGetModelsModelOutput() GetModelsModelOutput {
	return o
}

func (o GetModelsModelOutput) ToGetModelsModelOutputWithContext(ctx context.Context) GetModelsModelOutput {
	return o
}

// Created Time
func (o GetModelsModelOutput) Created() pulumi.IntOutput {
	return o.ApplyT(func(v GetModelsModel) int { return v.Created }).(pulumi.IntOutput)
}

// Model Identifier
func (o GetModelsModelOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelsModel) string { return v.Id }).(pulumi.StringOutput)
}

// Object Type
func (o GetModelsModelOutput) Object() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelsModel) string { return v.Object }).(pulumi.StringOutput)
}

// Model Owner
func (o GetModelsModelOutput) OwnedBy() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelsModel) string { return v.OwnedBy }).(pulumi.StringOutput)
}

// Parent
func (o GetModelsModelOutput) Parent() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelsModel) string { return v.Parent }).(pulumi.StringOutput)
}

// Permissions
func (o GetModelsModelOutput) Permissions() GetModelsModelPermissionArrayOutput {
	return o.ApplyT(func(v GetModelsModel) []GetModelsModelPermission { return v.Permissions }).(GetModelsModelPermissionArrayOutput)
}

// Root
func (o GetModelsModelOutput) Root() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelsModel) string { return v.Root }).(pulumi.StringOutput)
}

type GetModelsModelArrayOutput struct{ *pulumi.OutputState }

func (GetModelsModelArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetModelsModel)(nil)).Elem()
}

func (o GetModelsModelArrayOutput) ToGetModelsModelArrayOutput() GetModelsModelArrayOutput {
	return o
}

func (o GetModelsModelArrayOutput) ToGetModelsModelArrayOutputWithContext(ctx context.Context) GetModelsModelArrayOutput {
	return o
}

func (o GetModelsModelArrayOutput) Index(i pulumi.IntInput) GetModelsModelOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetModelsModel {
		return vs[0].([]GetModelsModel)[vs[1].(int)]
	}).(GetModelsModelOutput)
}

type GetModelsModelPermission struct {
	// Allow Create Engine
	AllowCreateEngine bool `pulumi:"allowCreateEngine"`
	// Allow Fine Tuning
	AllowFineTuning bool `pulumi:"allowFineTuning"`
	// Allow Logprobs
	AllowLogprobs bool `pulumi:"allowLogprobs"`
	// Allow Sampling
	AllowSampling bool `pulumi:"allowSampling"`
	// Allow Search Indices
	AllowSearchIndices bool `pulumi:"allowSearchIndices"`
	// Allow View
	AllowView bool `pulumi:"allowView"`
	// Created Time
	Created int `pulumi:"created"`
	// Permission Identifier
	Id string `pulumi:"id"`
	// Is Blocking
	IsBlocking bool `pulumi:"isBlocking"`
	// Object Type
	Object string `pulumi:"object"`
	// Organization
	Organization string `pulumi:"organization"`
}

// GetModelsModelPermissionInput is an input type that accepts GetModelsModelPermissionArgs and GetModelsModelPermissionOutput values.
// You can construct a concrete instance of `GetModelsModelPermissionInput` via:
//
//	GetModelsModelPermissionArgs{...}
type GetModelsModelPermissionInput interface {
	pulumi.Input

	ToGetModelsModelPermissionOutput() GetModelsModelPermissionOutput
	ToGetModelsModelPermissionOutputWithContext(context.Context) GetModelsModelPermissionOutput
}

type GetModelsModelPermissionArgs struct {
	// Allow Create Engine
	AllowCreateEngine pulumi.BoolInput `pulumi:"allowCreateEngine"`
	// Allow Fine Tuning
	AllowFineTuning pulumi.BoolInput `pulumi:"allowFineTuning"`
	// Allow Logprobs
	AllowLogprobs pulumi.BoolInput `pulumi:"allowLogprobs"`
	// Allow Sampling
	AllowSampling pulumi.BoolInput `pulumi:"allowSampling"`
	// Allow Search Indices
	AllowSearchIndices pulumi.BoolInput `pulumi:"allowSearchIndices"`
	// Allow View
	AllowView pulumi.BoolInput `pulumi:"allowView"`
	// Created Time
	Created pulumi.IntInput `pulumi:"created"`
	// Permission Identifier
	Id pulumi.StringInput `pulumi:"id"`
	// Is Blocking
	IsBlocking pulumi.BoolInput `pulumi:"isBlocking"`
	// Object Type
	Object pulumi.StringInput `pulumi:"object"`
	// Organization
	Organization pulumi.StringInput `pulumi:"organization"`
}

func (GetModelsModelPermissionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetModelsModelPermission)(nil)).Elem()
}

func (i GetModelsModelPermissionArgs) ToGetModelsModelPermissionOutput() GetModelsModelPermissionOutput {
	return i.ToGetModelsModelPermissionOutputWithContext(context.Background())
}

func (i GetModelsModelPermissionArgs) ToGetModelsModelPermissionOutputWithContext(ctx context.Context) GetModelsModelPermissionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetModelsModelPermissionOutput)
}

// GetModelsModelPermissionArrayInput is an input type that accepts GetModelsModelPermissionArray and GetModelsModelPermissionArrayOutput values.
// You can construct a concrete instance of `GetModelsModelPermissionArrayInput` via:
//
//	GetModelsModelPermissionArray{ GetModelsModelPermissionArgs{...} }
type GetModelsModelPermissionArrayInput interface {
	pulumi.Input

	ToGetModelsModelPermissionArrayOutput() GetModelsModelPermissionArrayOutput
	ToGetModelsModelPermissionArrayOutputWithContext(context.Context) GetModelsModelPermissionArrayOutput
}

type GetModelsModelPermissionArray []GetModelsModelPermissionInput

func (GetModelsModelPermissionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetModelsModelPermission)(nil)).Elem()
}

func (i GetModelsModelPermissionArray) ToGetModelsModelPermissionArrayOutput() GetModelsModelPermissionArrayOutput {
	return i.ToGetModelsModelPermissionArrayOutputWithContext(context.Background())
}

func (i GetModelsModelPermissionArray) ToGetModelsModelPermissionArrayOutputWithContext(ctx context.Context) GetModelsModelPermissionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetModelsModelPermissionArrayOutput)
}

type GetModelsModelPermissionOutput struct{ *pulumi.OutputState }

func (GetModelsModelPermissionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetModelsModelPermission)(nil)).Elem()
}

func (o GetModelsModelPermissionOutput) ToGetModelsModelPermissionOutput() GetModelsModelPermissionOutput {
	return o
}

func (o GetModelsModelPermissionOutput) ToGetModelsModelPermissionOutputWithContext(ctx context.Context) GetModelsModelPermissionOutput {
	return o
}

// Allow Create Engine
func (o GetModelsModelPermissionOutput) AllowCreateEngine() pulumi.BoolOutput {
	return o.ApplyT(func(v GetModelsModelPermission) bool { return v.AllowCreateEngine }).(pulumi.BoolOutput)
}

// Allow Fine Tuning
func (o GetModelsModelPermissionOutput) AllowFineTuning() pulumi.BoolOutput {
	return o.ApplyT(func(v GetModelsModelPermission) bool { return v.AllowFineTuning }).(pulumi.BoolOutput)
}

// Allow Logprobs
func (o GetModelsModelPermissionOutput) AllowLogprobs() pulumi.BoolOutput {
	return o.ApplyT(func(v GetModelsModelPermission) bool { return v.AllowLogprobs }).(pulumi.BoolOutput)
}

// Allow Sampling
func (o GetModelsModelPermissionOutput) AllowSampling() pulumi.BoolOutput {
	return o.ApplyT(func(v GetModelsModelPermission) bool { return v.AllowSampling }).(pulumi.BoolOutput)
}

// Allow Search Indices
func (o GetModelsModelPermissionOutput) AllowSearchIndices() pulumi.BoolOutput {
	return o.ApplyT(func(v GetModelsModelPermission) bool { return v.AllowSearchIndices }).(pulumi.BoolOutput)
}

// Allow View
func (o GetModelsModelPermissionOutput) AllowView() pulumi.BoolOutput {
	return o.ApplyT(func(v GetModelsModelPermission) bool { return v.AllowView }).(pulumi.BoolOutput)
}

// Created Time
func (o GetModelsModelPermissionOutput) Created() pulumi.IntOutput {
	return o.ApplyT(func(v GetModelsModelPermission) int { return v.Created }).(pulumi.IntOutput)
}

// Permission Identifier
func (o GetModelsModelPermissionOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelsModelPermission) string { return v.Id }).(pulumi.StringOutput)
}

// Is Blocking
func (o GetModelsModelPermissionOutput) IsBlocking() pulumi.BoolOutput {
	return o.ApplyT(func(v GetModelsModelPermission) bool { return v.IsBlocking }).(pulumi.BoolOutput)
}

// Object Type
func (o GetModelsModelPermissionOutput) Object() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelsModelPermission) string { return v.Object }).(pulumi.StringOutput)
}

// Organization
func (o GetModelsModelPermissionOutput) Organization() pulumi.StringOutput {
	return o.ApplyT(func(v GetModelsModelPermission) string { return v.Organization }).(pulumi.StringOutput)
}

type GetModelsModelPermissionArrayOutput struct{ *pulumi.OutputState }

func (GetModelsModelPermissionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetModelsModelPermission)(nil)).Elem()
}

func (o GetModelsModelPermissionArrayOutput) ToGetModelsModelPermissionArrayOutput() GetModelsModelPermissionArrayOutput {
	return o
}

func (o GetModelsModelPermissionArrayOutput) ToGetModelsModelPermissionArrayOutputWithContext(ctx context.Context) GetModelsModelPermissionArrayOutput {
	return o
}

func (o GetModelsModelPermissionArrayOutput) Index(i pulumi.IntInput) GetModelsModelPermissionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetModelsModelPermission {
		return vs[0].([]GetModelsModelPermission)[vs[1].(int)]
	}).(GetModelsModelPermissionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AssistantToolInput)(nil)).Elem(), AssistantToolArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AssistantToolArrayInput)(nil)).Elem(), AssistantToolArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AssistantToolFunctionInput)(nil)).Elem(), AssistantToolFunctionArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AssistantToolFunctionPtrInput)(nil)).Elem(), AssistantToolFunctionArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AssistantToolResourcesInput)(nil)).Elem(), AssistantToolResourcesArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AssistantToolResourcesPtrInput)(nil)).Elem(), AssistantToolResourcesArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AssistantToolResourcesCodeInterpreterInput)(nil)).Elem(), AssistantToolResourcesCodeInterpreterArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AssistantToolResourcesCodeInterpreterPtrInput)(nil)).Elem(), AssistantToolResourcesCodeInterpreterArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AssistantToolResourcesFileSearchInput)(nil)).Elem(), AssistantToolResourcesFileSearchArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AssistantToolResourcesFileSearchPtrInput)(nil)).Elem(), AssistantToolResourcesFileSearchArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AssistantToolResourcesFileSearchVectorStoresInput)(nil)).Elem(), AssistantToolResourcesFileSearchVectorStoresArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AssistantToolResourcesFileSearchVectorStoresPtrInput)(nil)).Elem(), AssistantToolResourcesFileSearchVectorStoresArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*FinetuningJobHyperparamsInput)(nil)).Elem(), FinetuningJobHyperparamsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*FinetuningJobHyperparamsPtrInput)(nil)).Elem(), FinetuningJobHyperparamsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetFilesFileInput)(nil)).Elem(), GetFilesFileArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetFilesFileArrayInput)(nil)).Elem(), GetFilesFileArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetFinetuningJobHyperparamsInput)(nil)).Elem(), GetFinetuningJobHyperparamsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetFinetuningJobsJobInput)(nil)).Elem(), GetFinetuningJobsJobArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetFinetuningJobsJobArrayInput)(nil)).Elem(), GetFinetuningJobsJobArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetFinetuningJobsJobHyperparamsInput)(nil)).Elem(), GetFinetuningJobsJobHyperparamsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetModelPermissionInput)(nil)).Elem(), GetModelPermissionArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetModelPermissionArrayInput)(nil)).Elem(), GetModelPermissionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetModelsModelInput)(nil)).Elem(), GetModelsModelArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetModelsModelArrayInput)(nil)).Elem(), GetModelsModelArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetModelsModelPermissionInput)(nil)).Elem(), GetModelsModelPermissionArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetModelsModelPermissionArrayInput)(nil)).Elem(), GetModelsModelPermissionArray{})
	pulumi.RegisterOutputType(AssistantToolOutput{})
	pulumi.RegisterOutputType(AssistantToolArrayOutput{})
	pulumi.RegisterOutputType(AssistantToolFunctionOutput{})
	pulumi.RegisterOutputType(AssistantToolFunctionPtrOutput{})
	pulumi.RegisterOutputType(AssistantToolResourcesOutput{})
	pulumi.RegisterOutputType(AssistantToolResourcesPtrOutput{})
	pulumi.RegisterOutputType(AssistantToolResourcesCodeInterpreterOutput{})
	pulumi.RegisterOutputType(AssistantToolResourcesCodeInterpreterPtrOutput{})
	pulumi.RegisterOutputType(AssistantToolResourcesFileSearchOutput{})
	pulumi.RegisterOutputType(AssistantToolResourcesFileSearchPtrOutput{})
	pulumi.RegisterOutputType(AssistantToolResourcesFileSearchVectorStoresOutput{})
	pulumi.RegisterOutputType(AssistantToolResourcesFileSearchVectorStoresPtrOutput{})
	pulumi.RegisterOutputType(FinetuningJobHyperparamsOutput{})
	pulumi.RegisterOutputType(FinetuningJobHyperparamsPtrOutput{})
	pulumi.RegisterOutputType(GetFilesFileOutput{})
	pulumi.RegisterOutputType(GetFilesFileArrayOutput{})
	pulumi.RegisterOutputType(GetFinetuningJobHyperparamsOutput{})
	pulumi.RegisterOutputType(GetFinetuningJobsJobOutput{})
	pulumi.RegisterOutputType(GetFinetuningJobsJobArrayOutput{})
	pulumi.RegisterOutputType(GetFinetuningJobsJobHyperparamsOutput{})
	pulumi.RegisterOutputType(GetModelPermissionOutput{})
	pulumi.RegisterOutputType(GetModelPermissionArrayOutput{})
	pulumi.RegisterOutputType(GetModelsModelOutput{})
	pulumi.RegisterOutputType(GetModelsModelArrayOutput{})
	pulumi.RegisterOutputType(GetModelsModelPermissionOutput{})
	pulumi.RegisterOutputType(GetModelsModelPermissionArrayOutput{})
}
