// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Openai.Outputs
{

    [OutputType]
    public sealed class AssistantToolFunction
    {
        /// <summary>
        /// A description of what the function does, used by the model to choose when and how to call the function.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The parameters the functions accepts, described as a JSON Schema object.
        /// </summary>
        public readonly string Parameters;

        [OutputConstructor]
        private AssistantToolFunction(
            string? description,

            string name,

            string parameters)
        {
            Description = description;
            Name = name;
            Parameters = parameters;
        }
    }
}
