// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Openai.Outputs
{

    [OutputType]
    public sealed class AssistantToolResources
    {
        /// <summary>
        /// Function definition for tools of type function.
        /// </summary>
        public readonly Outputs.AssistantToolResourcesCodeInterpreter? CodeInterpreter;
        /// <summary>
        /// Function definition for tools of type function.
        /// </summary>
        public readonly Outputs.AssistantToolResourcesFileSearch? FileSearch;

        [OutputConstructor]
        private AssistantToolResources(
            Outputs.AssistantToolResourcesCodeInterpreter? codeInterpreter,

            Outputs.AssistantToolResourcesFileSearch? fileSearch)
        {
            CodeInterpreter = codeInterpreter;
            FileSearch = fileSearch;
        }
    }
}
