// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Openai.Outputs
{

    [OutputType]
    public sealed class GetFinetuningJobsJobHyperparamsResult
    {
        /// <summary>
        /// N Epochs
        /// </summary>
        public readonly int NEpochs;

        [OutputConstructor]
        private GetFinetuningJobsJobHyperparamsResult(int nEpochs)
        {
            NEpochs = nEpochs;
        }
    }
}
