// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Openai.Outputs
{

    [OutputType]
    public sealed class GetFinetuningJobsJobResult
    {
        /// <summary>
        /// Created Time
        /// </summary>
        public readonly int CreatedAt;
        /// <summary>
        /// Fine-Tuned Model ID
        /// </summary>
        public readonly string FineTunedModel;
        /// <summary>
        /// Finished Time
        /// </summary>
        public readonly int FinishedAt;
        /// <summary>
        /// Hyperparams
        /// </summary>
        public readonly Outputs.GetFinetuningJobsJobHyperparamsResult Hyperparams;
        /// <summary>
        /// Fine-Tuning Job Identifier
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Model ID
        /// </summary>
        public readonly string Model;
        /// <summary>
        /// Object Type
        /// </summary>
        public readonly string Object;
        /// <summary>
        /// Organization ID
        /// </summary>
        public readonly string OrganizationId;
        /// <summary>
        /// Result Files
        /// </summary>
        public readonly ImmutableArray<string> ResultFiles;
        /// <summary>
        /// Status
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// Trained Tokens
        /// </summary>
        public readonly int TrainedTokens;
        /// <summary>
        /// Training File
        /// </summary>
        public readonly string TrainingFile;
        /// <summary>
        /// Validation File
        /// </summary>
        public readonly string ValidationFile;

        [OutputConstructor]
        private GetFinetuningJobsJobResult(
            int createdAt,

            string fineTunedModel,

            int finishedAt,

            Outputs.GetFinetuningJobsJobHyperparamsResult hyperparams,

            string id,

            string model,

            string @object,

            string organizationId,

            ImmutableArray<string> resultFiles,

            string status,

            int trainedTokens,

            string trainingFile,

            string validationFile)
        {
            CreatedAt = createdAt;
            FineTunedModel = fineTunedModel;
            FinishedAt = finishedAt;
            Hyperparams = hyperparams;
            Id = id;
            Model = model;
            Object = @object;
            OrganizationId = organizationId;
            ResultFiles = resultFiles;
            Status = status;
            TrainedTokens = trainedTokens;
            TrainingFile = trainingFile;
            ValidationFile = validationFile;
        }
    }
}
