// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Openai.Outputs
{

    [OutputType]
    public sealed class GetModelsModelPermissionResult
    {
        /// <summary>
        /// Allow Create Engine
        /// </summary>
        public readonly bool AllowCreateEngine;
        /// <summary>
        /// Allow Fine Tuning
        /// </summary>
        public readonly bool AllowFineTuning;
        /// <summary>
        /// Allow Logprobs
        /// </summary>
        public readonly bool AllowLogprobs;
        /// <summary>
        /// Allow Sampling
        /// </summary>
        public readonly bool AllowSampling;
        /// <summary>
        /// Allow Search Indices
        /// </summary>
        public readonly bool AllowSearchIndices;
        /// <summary>
        /// Allow View
        /// </summary>
        public readonly bool AllowView;
        /// <summary>
        /// Created Time
        /// </summary>
        public readonly int Created;
        /// <summary>
        /// Permission Identifier
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Is Blocking
        /// </summary>
        public readonly bool IsBlocking;
        /// <summary>
        /// Object Type
        /// </summary>
        public readonly string Object;
        /// <summary>
        /// Organization
        /// </summary>
        public readonly string Organization;

        [OutputConstructor]
        private GetModelsModelPermissionResult(
            bool allowCreateEngine,

            bool allowFineTuning,

            bool allowLogprobs,

            bool allowSampling,

            bool allowSearchIndices,

            bool allowView,

            int created,

            string id,

            bool isBlocking,

            string @object,

            string organization)
        {
            AllowCreateEngine = allowCreateEngine;
            AllowFineTuning = allowFineTuning;
            AllowLogprobs = allowLogprobs;
            AllowSampling = allowSampling;
            AllowSearchIndices = allowSearchIndices;
            AllowView = allowView;
            Created = created;
            Id = id;
            IsBlocking = isBlocking;
            Object = @object;
            Organization = organization;
        }
    }
}
