// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Openai.Outputs
{

    [OutputType]
    public sealed class GetModelsModelResult
    {
        /// <summary>
        /// Created Time
        /// </summary>
        public readonly int Created;
        /// <summary>
        /// Model Identifier
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Object Type
        /// </summary>
        public readonly string Object;
        /// <summary>
        /// Model Owner
        /// </summary>
        public readonly string OwnedBy;
        /// <summary>
        /// Parent
        /// </summary>
        public readonly string Parent;
        /// <summary>
        /// Permissions
        /// </summary>
        public readonly ImmutableArray<Outputs.GetModelsModelPermissionResult> Permissions;
        /// <summary>
        /// Root
        /// </summary>
        public readonly string Root;

        [OutputConstructor]
        private GetModelsModelResult(
            int created,

            string id,

            string @object,

            string ownedBy,

            string parent,

            ImmutableArray<Outputs.GetModelsModelPermissionResult> permissions,

            string root)
        {
            Created = created;
            Id = id;
            Object = @object;
            OwnedBy = ownedBy;
            Parent = parent;
            Permissions = permissions;
            Root = root;
        }
    }
}
