// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Openai.Inputs
{

    public sealed class AssistantToolResourcesCodeInterpreterGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("fileIds")]
        private InputList<string>? _fileIds;

        /// <summary>
        /// A list of file IDs attached to this assistant. There can be a maximum of 20 files attached to the assistant. Files are ordered by their creation date in ascending order.
        /// </summary>
        public InputList<string> FileIds
        {
            get => _fileIds ?? (_fileIds = new InputList<string>());
            set => _fileIds = value;
        }

        public AssistantToolResourcesCodeInterpreterGetArgs()
        {
        }
        public static new AssistantToolResourcesCodeInterpreterGetArgs Empty => new AssistantToolResourcesCodeInterpreterGetArgs();
    }
}
