// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Openai.Inputs
{

    public sealed class AssistantToolResourcesGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Function definition for tools of type function.
        /// </summary>
        [Input("codeInterpreter")]
        public Input<Inputs.AssistantToolResourcesCodeInterpreterGetArgs>? CodeInterpreter { get; set; }

        /// <summary>
        /// Function definition for tools of type function.
        /// </summary>
        [Input("fileSearch")]
        public Input<Inputs.AssistantToolResourcesFileSearchGetArgs>? FileSearch { get; set; }

        public AssistantToolResourcesGetArgs()
        {
        }
        public static new AssistantToolResourcesGetArgs Empty => new AssistantToolResourcesGetArgs();
    }
}
