// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Openai.Inputs
{

    public sealed class FinetuningJobHyperparamsGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// N Epochs
        /// </summary>
        [Input("nEpochs")]
        public Input<int>? NEpochs { get; set; }

        public FinetuningJobHyperparamsGetArgs()
        {
        }
        public static new FinetuningJobHyperparamsGetArgs Empty => new FinetuningJobHyperparamsGetArgs();
    }
}
