// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * File resource
 */
export class File extends pulumi.CustomResource {
    /**
     * Get an existing File resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FileState, opts?: pulumi.CustomResourceOptions): File {
        return new File(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'openai:index/file:File';

    /**
     * Returns true if the given object is an instance of File.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is File {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === File.__pulumiType;
    }

    /**
     * File size in bytes
     */
    public /*out*/ readonly bytes!: pulumi.Output<number>;
    /**
     * Created Time
     */
    public /*out*/ readonly created!: pulumi.Output<number>;
    /**
     * Filename
     */
    public /*out*/ readonly filename!: pulumi.Output<string>;
    /**
     * Filename
     */
    public readonly filepath!: pulumi.Output<string>;
    /**
     * Object Type
     */
    public /*out*/ readonly object!: pulumi.Output<string>;
    /**
     * Intended use of file. Use 'fine-tune' for Fine-tuning
     */
    public /*out*/ readonly purpose!: pulumi.Output<string>;

    /**
     * Create a File resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FileArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FileArgs | FileState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FileState | undefined;
            resourceInputs["bytes"] = state ? state.bytes : undefined;
            resourceInputs["created"] = state ? state.created : undefined;
            resourceInputs["filename"] = state ? state.filename : undefined;
            resourceInputs["filepath"] = state ? state.filepath : undefined;
            resourceInputs["object"] = state ? state.object : undefined;
            resourceInputs["purpose"] = state ? state.purpose : undefined;
        } else {
            const args = argsOrState as FileArgs | undefined;
            if ((!args || args.filepath === undefined) && !opts.urn) {
                throw new Error("Missing required property 'filepath'");
            }
            resourceInputs["filepath"] = args ? args.filepath : undefined;
            resourceInputs["bytes"] = undefined /*out*/;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["filename"] = undefined /*out*/;
            resourceInputs["object"] = undefined /*out*/;
            resourceInputs["purpose"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(File.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering File resources.
 */
export interface FileState {
    /**
     * File size in bytes
     */
    bytes?: pulumi.Input<number>;
    /**
     * Created Time
     */
    created?: pulumi.Input<number>;
    /**
     * Filename
     */
    filename?: pulumi.Input<string>;
    /**
     * Filename
     */
    filepath?: pulumi.Input<string>;
    /**
     * Object Type
     */
    object?: pulumi.Input<string>;
    /**
     * Intended use of file. Use 'fine-tune' for Fine-tuning
     */
    purpose?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a File resource.
 */
export interface FileArgs {
    /**
     * Filename
     */
    filepath: pulumi.Input<string>;
}
