// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Fine Tuning Job resource
 */
export class FinetuningJob extends pulumi.CustomResource {
    /**
     * Get an existing FinetuningJob resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FinetuningJobState, opts?: pulumi.CustomResourceOptions): FinetuningJob {
        return new FinetuningJob(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'openai:index/finetuningJob:FinetuningJob';

    /**
     * Returns true if the given object is an instance of FinetuningJob.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is FinetuningJob {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === FinetuningJob.__pulumiType;
    }

    /**
     * Created Time
     */
    public /*out*/ readonly createdAt!: pulumi.Output<number>;
    /**
     * Fine Tuned Model
     */
    public /*out*/ readonly fineTunedModel!: pulumi.Output<string>;
    /**
     * Finished Time
     */
    public /*out*/ readonly finishedAt!: pulumi.Output<number>;
    /**
     * Hyperparams
     */
    public /*out*/ readonly hyperparams!: pulumi.Output<outputs.FinetuningJobHyperparams>;
    /**
     * Model Identifier
     */
    public readonly model!: pulumi.Output<string | undefined>;
    /**
     * Object Type
     */
    public /*out*/ readonly object!: pulumi.Output<string>;
    /**
     * Organization Id
     */
    public /*out*/ readonly organizationId!: pulumi.Output<string>;
    /**
     * Result Files
     */
    public /*out*/ readonly resultFiles!: pulumi.Output<string[]>;
    /**
     * Status
     */
    public /*out*/ readonly status!: pulumi.Output<string>;
    /**
     * Suffix
     */
    public /*out*/ readonly suffix!: pulumi.Output<string>;
    /**
     * Trained Tokens
     */
    public /*out*/ readonly trainedTokens!: pulumi.Output<number>;
    /**
     * Training File Identifier
     */
    public readonly trainingFile!: pulumi.Output<string | undefined>;
    /**
     * Validation File Identifier
     */
    public readonly validationFile!: pulumi.Output<string | undefined>;
    /**
     * Wait for Fine Tuning Job completion
     */
    public readonly wait!: pulumi.Output<boolean | undefined>;

    /**
     * Create a FinetuningJob resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: FinetuningJobArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FinetuningJobArgs | FinetuningJobState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FinetuningJobState | undefined;
            resourceInputs["createdAt"] = state ? state.createdAt : undefined;
            resourceInputs["fineTunedModel"] = state ? state.fineTunedModel : undefined;
            resourceInputs["finishedAt"] = state ? state.finishedAt : undefined;
            resourceInputs["hyperparams"] = state ? state.hyperparams : undefined;
            resourceInputs["model"] = state ? state.model : undefined;
            resourceInputs["object"] = state ? state.object : undefined;
            resourceInputs["organizationId"] = state ? state.organizationId : undefined;
            resourceInputs["resultFiles"] = state ? state.resultFiles : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
            resourceInputs["suffix"] = state ? state.suffix : undefined;
            resourceInputs["trainedTokens"] = state ? state.trainedTokens : undefined;
            resourceInputs["trainingFile"] = state ? state.trainingFile : undefined;
            resourceInputs["validationFile"] = state ? state.validationFile : undefined;
            resourceInputs["wait"] = state ? state.wait : undefined;
        } else {
            const args = argsOrState as FinetuningJobArgs | undefined;
            resourceInputs["model"] = args ? args.model : undefined;
            resourceInputs["trainingFile"] = args ? args.trainingFile : undefined;
            resourceInputs["validationFile"] = args ? args.validationFile : undefined;
            resourceInputs["wait"] = args ? args.wait : undefined;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["fineTunedModel"] = undefined /*out*/;
            resourceInputs["finishedAt"] = undefined /*out*/;
            resourceInputs["hyperparams"] = undefined /*out*/;
            resourceInputs["object"] = undefined /*out*/;
            resourceInputs["organizationId"] = undefined /*out*/;
            resourceInputs["resultFiles"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["suffix"] = undefined /*out*/;
            resourceInputs["trainedTokens"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(FinetuningJob.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering FinetuningJob resources.
 */
export interface FinetuningJobState {
    /**
     * Created Time
     */
    createdAt?: pulumi.Input<number>;
    /**
     * Fine Tuned Model
     */
    fineTunedModel?: pulumi.Input<string>;
    /**
     * Finished Time
     */
    finishedAt?: pulumi.Input<number>;
    /**
     * Hyperparams
     */
    hyperparams?: pulumi.Input<inputs.FinetuningJobHyperparams>;
    /**
     * Model Identifier
     */
    model?: pulumi.Input<string>;
    /**
     * Object Type
     */
    object?: pulumi.Input<string>;
    /**
     * Organization Id
     */
    organizationId?: pulumi.Input<string>;
    /**
     * Result Files
     */
    resultFiles?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Status
     */
    status?: pulumi.Input<string>;
    /**
     * Suffix
     */
    suffix?: pulumi.Input<string>;
    /**
     * Trained Tokens
     */
    trainedTokens?: pulumi.Input<number>;
    /**
     * Training File Identifier
     */
    trainingFile?: pulumi.Input<string>;
    /**
     * Validation File Identifier
     */
    validationFile?: pulumi.Input<string>;
    /**
     * Wait for Fine Tuning Job completion
     */
    wait?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a FinetuningJob resource.
 */
export interface FinetuningJobArgs {
    /**
     * Model Identifier
     */
    model?: pulumi.Input<string>;
    /**
     * Training File Identifier
     */
    trainingFile?: pulumi.Input<string>;
    /**
     * Validation File Identifier
     */
    validationFile?: pulumi.Input<string>;
    /**
     * Wait for Fine Tuning Job completion
     */
    wait?: pulumi.Input<boolean>;
}
