// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Files data source
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as openai from "@pulumi/openai";
 *
 * const test = openai.getFiles({});
 * ```
 */
export function getFiles(opts?: pulumi.InvokeOptions): Promise<GetFilesResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("openai:index/getFiles:getFiles", {
    }, opts);
}

/**
 * A collection of values returned by getFiles.
 */
export interface GetFilesResult {
    /**
     * Files
     */
    readonly files: outputs.GetFilesFile[];
    /**
     * Files identifier
     */
    readonly id: string;
}
/**
 * Files data source
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as openai from "@pulumi/openai";
 *
 * const test = openai.getFiles({});
 * ```
 */
export function getFilesOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetFilesResult> {
    return pulumi.output(getFiles(opts))
}
