// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Fine-Tuning Job data source
 */
export function getFinetuningJob(args: GetFinetuningJobArgs, opts?: pulumi.InvokeOptions): Promise<GetFinetuningJobResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("openai:index/getFinetuningJob:getFinetuningJob", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getFinetuningJob.
 */
export interface GetFinetuningJobArgs {
    /**
     * Fine Tuning Job Identifier
     */
    id: string;
}

/**
 * A collection of values returned by getFinetuningJob.
 */
export interface GetFinetuningJobResult {
    /**
     * Created Time
     */
    readonly createdAt: number;
    /**
     * Fine-Tuned Model ID
     */
    readonly fineTunedModel: string;
    /**
     * Finished Time
     */
    readonly finishedAt: number;
    /**
     * Hyperparams
     */
    readonly hyperparams: outputs.GetFinetuningJobHyperparams;
    /**
     * Fine Tuning Job Identifier
     */
    readonly id: string;
    /**
     * Model ID
     */
    readonly model: string;
    /**
     * Object Type
     */
    readonly object: string;
    /**
     * Organization ID
     */
    readonly organizationId: string;
    /**
     * Result Files
     */
    readonly resultFiles: string[];
    /**
     * Status
     */
    readonly status: string;
    /**
     * Trained Tokens
     */
    readonly trainedTokens: number;
    /**
     * Training File
     */
    readonly trainingFile: string;
    /**
     * Validation File
     */
    readonly validationFile: string;
}
/**
 * Fine-Tuning Job data source
 */
export function getFinetuningJobOutput(args: GetFinetuningJobOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetFinetuningJobResult> {
    return pulumi.output(args).apply((a: any) => getFinetuningJob(a, opts))
}

/**
 * A collection of arguments for invoking getFinetuningJob.
 */
export interface GetFinetuningJobOutputArgs {
    /**
     * Fine Tuning Job Identifier
     */
    id: pulumi.Input<string>;
}
