// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Models data source
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as openai from "@pulumi/openai";
 *
 * const models = openai.getModels({});
 * export const modelCount = models.then(models => models.models).length;
 * ```
 */
export function getModels(opts?: pulumi.InvokeOptions): Promise<GetModelsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("openai:index/getModels:getModels", {
    }, opts);
}

/**
 * A collection of values returned by getModels.
 */
export interface GetModelsResult {
    /**
     * Models identifier
     */
    readonly id: string;
    /**
     * Models
     */
    readonly models: outputs.GetModelsModel[];
}
/**
 * Models data source
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as openai from "@pulumi/openai";
 *
 * const models = openai.getModels({});
 * export const modelCount = models.then(models => models.models).length;
 * ```
 */
export function getModelsOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetModelsResult> {
    return pulumi.output(getModels(opts))
}
